package Users;

import Users.Role;
import HelperFunction.SessionUser;
import HelperFunction.FileHandling;
import MedicalManager.*;
import Doctor.Doctor;
import Doctor.DoctorDashboard;
import Admin.Admin;
import Admin.AdminDashboard;
import java.util.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import Patient.*;

public class UserLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UserLogin.class.getName());

    public UserLogin() {
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblHospitalName = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblUserID1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        pwdPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HMS Patient Portal v1.0 ");
        setResizable(false);
        getContentPane().setLayout(null);

        pnlLeft.setBackground(new java.awt.Color(38, 117, 154));
        pnlLeft.setToolTipText("");
        pnlLeft.setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        lblLogo.setToolTipText("");
        pnlLeft.add(lblLogo);
        lblLogo.setBounds(140, 170, 106, 94);

        lblHospitalName.setBackground(new java.awt.Color(255, 255, 255));
        lblHospitalName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHospitalName.setText("APU Medical Centre");
        pnlLeft.add(lblHospitalName);
        lblHospitalName.setBounds(90, 270, 240, 24);
        lblHospitalName.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(pnlLeft);
        pnlLeft.setBounds(0, 0, 393, 600);

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setMinimumSize(new java.awt.Dimension(800, 600));
        pnlRight.setPreferredSize(new java.awt.Dimension(800, 600));
        pnlRight.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitle.setText("AMC LOGIN PORTAL");
        pnlRight.add(lblTitle);
        lblTitle.setBounds(70, 130, 272, 80);

        lblPassword.setText("Password");
        lblPassword.setToolTipText("");
        pnlRight.add(lblPassword);
        lblPassword.setBounds(40, 290, 120, 16);

        lblUserID1.setText("E-Mail");
        pnlRight.add(lblUserID1);
        lblUserID1.setBounds(40, 220, 120, 16);

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlRight.add(txtEmail);
        txtEmail.setBounds(40, 240, 320, 30);

        btnLogin.setBackground(new java.awt.Color(38, 117, 154));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setFocusPainted(false);
        btnLogin.setRolloverEnabled(false);
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        pnlRight.add(btnLogin);
        btnLogin.setBounds(80, 410, 240, 36);
        pnlRight.add(pwdPassword);
        pwdPassword.setBounds(40, 310, 320, 30);

        getContentPane().add(pnlRight);
        pnlRight.setBounds(393, 0, 410, 600);

        setBounds(0, 0, 816, 609);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String inputEmail = txtEmail.getText().trim();
        String password = new String(pwdPassword.getPassword());

        if (inputEmail.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your email and password.");
            return;
        }
        TreeMap<Integer, ArrayList<String>> users = FileHandling.readAllRecords("Users.txt");
        if (users != null) {
            for (Integer id : users.keySet()) {
                ArrayList<String> u = users.get(id);

                boolean emailMatch = u.get(5).equalsIgnoreCase(inputEmail);
                boolean passMatch = u.get(6).equals(password);
                boolean isActive = u.get(8).equals("0");

                if (emailMatch && passMatch && isActive) {

                    // Extract user details
                    String first = u.get(0);
                    String last = u.get(1);
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
                    LocalDate dob = LocalDate.parse(u.get(2), formatter);
                    String gender = u.get(3);
                    String phone = u.get(4);
                    String email = u.get(5);
                    Role role = Role.valueOf(u.get(7));

                    switch (role) {
                        case MedicalManager:
                            MedicalManager manager = new MedicalManager(
                                    id, first, last, phone, email, password, gender, dob, role);
                            SessionUser.login(manager);

                            new ManagerDashboard().setVisible(true);
                            this.dispose();
                            return;

                        case Patient:
                            Patient patient = new Patient(id, first, last, phone, email, password, gender, dob, role);
                            SessionUser.login(patient);
                            new PatientDashboard().setVisible(true);
                            this.dispose();
                            return;

                        case Doctor:
                            Doctor doctor = new Doctor(id, first, last, phone, email, password, gender, dob, role);
                            SessionUser.login(doctor);
                            new DoctorDashboard().setVisible(true);
                            this.dispose();
                            return;

                        case Admin:
                            Admin admin = new Admin(id, first, last, phone, email, password, gender, dob, role);
                            SessionUser.login(admin);
                            new AdminDashboard().setVisible(true);
                            this.dispose();
                            return;
                    }
                }
            }
        }
        JOptionPane.showMessageDialog(this, "Invalid Email or Password.");
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        javax.swing.UIManager.put("Button.focus", new java.awt.Color(0, 0, 0, 0));
        javax.swing.UIManager.put("RadioButton.focus", new java.awt.Color(0, 0, 0, 0));

        /* Create and display the form */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UserLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserID1;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
