
package MedicalManager;

import HelperFunction.SessionUser;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import java.util.Date;


public class ManagerProfile extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManagerProfile.class.getName());
    private MedicalManager manager = (MedicalManager) SessionUser.getCurrentUser();

    /**
     * Creates new form ManagerDashboard
     */
    public ManagerProfile() {
        initComponents();
        loadProfileData();
    }
    
    private void setupDobSpinner(){
        JSpinner.DateEditor dobEditor = new JSpinner.DateEditor(dobSpinner, "dd-MM-yyyy");
        dobSpinner.setEditor(dobEditor);
    }
    
    private void loadProfileData() {
        userIDLbl.setText(String.format("USER%03d", manager.getUserID()));
        firstNameTf.setText(manager.getFirst());
        lastNameTf.setText(manager.getLast());
        emailTf.setText(manager.getEmail());
        phoneTf.setText(manager.getPhone());
        passwordField.setText(manager.getPassword());
        confirmPasswordField.setText(manager.getPassword());
        
        Date dobDate = java.sql.Date.valueOf(manager.getDob());
        dobSpinner.setValue(dobDate);
        
        if("Female".equalsIgnoreCase(manager.getGender())){
            femaleRadio.setSelected(true);
        }else {
            maleRadio.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        genderGrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lastNameTf = new javax.swing.JTextField();
        userIDLbl = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        firstNameTf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        emailTf = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dashboardBtn = new javax.swing.JButton();
        departmentBtn = new javax.swing.JButton();
        shiftBtn = new javax.swing.JButton();
        reportBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        logoutBtn1 = new javax.swing.JButton();
        phoneTf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        confirmPasswordField = new javax.swing.JPasswordField();
        dobSpinner = new javax.swing.JSpinner();

        jLabel4.setText("jLabel3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Edit Personal Profile");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("MANAGER ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("LAST NAME");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 130, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("CONFIRM PASSWORD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("EMAIL ADDRESS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, -1));

        lastNameTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(lastNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 290, -1));

        userIDLbl.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        userIDLbl.setText("USER001");
        getContentPane().add(userIDLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 110, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("DATE OF BIRTH");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 170, -1));

        firstNameTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(firstNameTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 300, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("PHONE NUMBER");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 180, -1));

        passwordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordField.setText("jPasswordField1");
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 300, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("FIRST NAME");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("GENDER");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 110, -1));

        genderGrp.add(maleRadio);
        maleRadio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maleRadio.setText("Male");
        getContentPane().add(maleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, -1, -1));

        genderGrp.add(femaleRadio);
        femaleRadio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        femaleRadio.setText("Female");
        getContentPane().add(femaleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));

        emailTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(emailTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 300, -1));

        saveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveBtn.setText("Save Profile Changes");
        saveBtn.addActionListener(this::saveBtnActionPerformed);
        getContentPane().add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("APU Medical Centre");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, -1, -1));

        jPanel2.setBackground(new java.awt.Color(38, 117, 154));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dashboardBtn.setText("Dashboard");
        dashboardBtn.addActionListener(this::dashboardBtnActionPerformed);
        jPanel2.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        departmentBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        departmentBtn.setText("Departments");
        departmentBtn.addActionListener(this::departmentBtnActionPerformed);
        jPanel2.add(departmentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        shiftBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        shiftBtn.setText("Shift Rosters");
        shiftBtn.addActionListener(this::shiftBtnActionPerformed);
        jPanel2.add(shiftBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        reportBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        reportBtn.setText("Reports");
        reportBtn.addActionListener(this::reportBtnActionPerformed);
        jPanel2.add(reportBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        profileBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        profileBtn.setText("Profile");
        jPanel2.add(profileBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, -1, -1));

        logoutBtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logoutBtn1.setText("Logout");
        logoutBtn1.addActionListener(this::logoutBtn1ActionPerformed);
        jPanel2.add(logoutBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        phoneTf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(phoneTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 300, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("PASSWORD");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        confirmPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmPasswordField.setText("jPasswordField1");
        getContentPane().add(confirmPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 290, -1));

        dobSpinner.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dobSpinner.setModel(new javax.swing.SpinnerDateModel());
        getContentPane().add(dobSpinner, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 290, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
        // TODO add your handling code here:
        ManagerDashboard dashboard = new ManagerDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void departmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentBtnActionPerformed
        // TODO add your handling code here:
        ManageDepartments departmentPage = new ManageDepartments();
        departmentPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_departmentBtnActionPerformed

    private void shiftBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shiftBtnActionPerformed
        // TODO add your handling code here:
        ManageShifts shiftPage = new ManageShifts();
        shiftPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_shiftBtnActionPerformed

    private void reportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportBtnActionPerformed
        // TODO add your handling code here:
        ViewReports reportPage = new ViewReports();
        reportPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reportBtnActionPerformed

    private void logoutBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtn1ActionPerformed
        // TODO add your handling code here:
        int confirmLogout = javax.swing.JOptionPane.showConfirmDialog(this,
                "Are you sure you want to log out?",
                "Logout Confirmation",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if(confirmLogout == javax.swing.JOptionPane.YES_OPTION) {
            SessionUser.logout();
            new Users.UserLogin().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_logoutBtn1ActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String first = firstNameTf.getText().trim();
        String last = lastNameTf.getText().trim();
        String email = emailTf.getText().trim();
        String phone = phoneTf.getText();
        String gender = maleRadio.isSelected() ? "Male" : "Female"; // variable = (condition) ? if_true : if_false
        String password = new String(passwordField.getPassword());
        String confirmPassword = new String(confirmPasswordField.getPassword());
        
        if (first.isEmpty() || last.isEmpty() || email.isEmpty() || phone.isEmpty() ||
                password.isEmpty() || confirmPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Missing Information", JOptionPane.WARNING_MESSAGE);
            return; // stop saving process
        }
        
        Date selectedDate = (java.util.Date) dobSpinner.getValue();
        LocalDate dob = selectedDate.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
        if(dob.isAfter(LocalDate.now())){
            JOptionPane.showMessageDialog(this, "Date of Birth cannot be in the future",
                    "Invalid Date", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!password.equals(confirmPassword)){
            JOptionPane.showMessageDialog(this, "Passwords do not match. Please try again.",
                    "Password Mismatch", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        if(!email.matches(emailRegex)){
            JOptionPane.showMessageDialog(this,"Please Enter a Valid Email (user@example.com)",
                    "Invalid Email", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String phoneRegex = "^01[0-9]-[0-9]{7,8}$";
        if(!phone.matches(phoneRegex)){
            JOptionPane.showMessageDialog(this, "Please Enter Valid Phone Number (e.g., 012-3456789)",
                    "Invalid Phone Number", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        boolean updateSuccess = manager.updateProfile(first, last, phone, email, password, gender, dob);
        if(updateSuccess) {
            JOptionPane.showMessageDialog(this, "Profile Updated Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Unable to update profile.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManagerProfile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField confirmPasswordField;
    private javax.swing.JButton dashboardBtn;
    private javax.swing.JButton departmentBtn;
    private javax.swing.JSpinner dobSpinner;
    private javax.swing.JTextField emailTf;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JTextField firstNameTf;
    private javax.swing.ButtonGroup genderGrp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastNameTf;
    private javax.swing.JButton logoutBtn1;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField phoneTf;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton reportBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton shiftBtn;
    private javax.swing.JLabel userIDLbl;
    // End of variables declaration//GEN-END:variables
}
