
package MedicalManager;


public class ManageDepartments extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageDepartments.class.getName());

    public ManageDepartments() {
        initComponents();
        
        this.getContentPane().setBackground(new java.awt.Color(248,250,252));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        overviewBtn = new javax.swing.JButton();
        departmentsBtn = new javax.swing.JButton();
        rostersBtn = new javax.swing.JButton();
        reportsBtn = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(248, 250, 252));
        getContentPane().setLayout(null);

        jLabel1.setText("Create or update specialised clinical departments and edit department details.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 80, 420, 16);

        overviewBtn.setText("Overview");
        getContentPane().add(overviewBtn);
        overviewBtn.setBounds(200, 10, 79, 23);

        departmentsBtn.setText("Departments");
        getContentPane().add(departmentsBtn);
        departmentsBtn.setBounds(300, 10, 98, 23);

        rostersBtn.setText("Rosters");
        getContentPane().add(rostersBtn);
        rostersBtn.setBounds(420, 10, 72, 23);

        reportsBtn.setText("Reports");
        getContentPane().add(reportsBtn);
        reportsBtn.setBounds(500, 10, 72, 23);

        profileBtn.setText("Profile");
        getContentPane().add(profileBtn);
        profileBtn.setBounds(590, 10, 72, 23);

        logoutBtn.setText("Logout");
        getContentPane().add(logoutBtn);
        logoutBtn.setBounds(680, 10, 72, 23);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Clinical Departments Management");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 290, 25);

        jLabel3.setText("APU Medical Centre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 10, 106, 16);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(420, 130, 400, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageDepartments().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton departmentsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton overviewBtn;
    private javax.swing.JButton profileBtn;
    private javax.swing.JButton reportsBtn;
    private javax.swing.JButton rostersBtn;
    // End of variables declaration//GEN-END:variables
}
