/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Doctor;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sascha
 */
public class CasesDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CasesDialog.class.getName());

    private DoctorServices doctor;
    private int caseId = -1;

    /**
     * Creates new form CasesDialog
     */
    public CasesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    // Used by the doctor dashboard to open one specific case
    public CasesDialog(java.awt.Frame parent, boolean modal, DoctorServices doctor, int caseId) {
        super(parent, modal);
        initComponents();
        this.doctor = doctor;
        this.caseId = caseId;

        if (!doctor.loadCase(caseId)) {
            JOptionPane.showMessageDialog(this, "This case could not be found.");
            dispose();
            return;
        }
        refresh();
    }

    // Redraws every field from the doctor object's current data
    private void refresh() {
        lblCaseHeader.setText(doctor.getCaseTitle());
        lblCaseMeta.setText(doctor.getCaseMeta());
        lblCaseStatusBadge.setText(doctor.isCaseOpen() ? "OPEN" : "CLOSED");
        lblCaseRoleNote.setText(doctor.getCaseRoleNote());

        String[] patientInfo = doctor.getCasePatient(); // {age, gender, bloodType, allergies}
        lblPatientAge.setText("Age: " + patientInfo[0]);
        lblPatientGender.setText("Gender: " + patientInfo[1]);
        lblPatientBloodType.setText("Blood Type: " + patientInfo[2]);
        lblPatientAllergies.setText("Allergies: " + patientInfo[3]);

        txtCaseSummary.setText(doctor.getCaseSummary());
        boolean inCharge = doctor.isCaseInCharge();
        boolean open = doctor.isCaseOpen();
        txtCaseSummary.setEditable(inCharge && open);
        btnSaveSummary.setEnabled(inCharge && open);
        btnCloseCase.setEnabled(inCharge && open);

        DefaultTableModel consultModel = (DefaultTableModel) tblCaseConsultations.getModel();
        consultModel.setRowCount(0);
        for (Object[] row : doctor.getCaseConsultRows()) {
            consultModel.addRow(row);
        }

        DefaultTableModel testModel = (DefaultTableModel) tblCaseDiagnostics.getModel();
        testModel.setRowCount(0);
        for (Object[] row : doctor.getCaseTestRows()) {
            testModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCaseHeader = new javax.swing.JLabel();
        lblCaseMeta = new javax.swing.JLabel();
        lblCaseStatusBadge = new javax.swing.JLabel();
        lblSummaryHeader = new javax.swing.JLabel();
        scrCaseSummary = new javax.swing.JScrollPane();
        txtCaseSummary = new javax.swing.JTextArea();
        btnSaveSummary = new javax.swing.JButton();
        lblDiagnosticsHeader = new javax.swing.JLabel();
        scrCaseConsultations = new javax.swing.JScrollPane();
        tblCaseConsultations = new javax.swing.JTable();
        lblConsultationsHeader = new javax.swing.JLabel();
        scrCaseDiagnostics = new javax.swing.JScrollPane();
        tblCaseDiagnostics = new javax.swing.JTable();
        btnViewConsultation = new javax.swing.JButton();
        btnCloseCase = new javax.swing.JButton();
        lblCaseRoleNote = new javax.swing.JLabel();
        lblPatientInfoHeader = new javax.swing.JLabel();
        lblPatientAge = new javax.swing.JLabel();
        lblPatientGender = new javax.swing.JLabel();
        lblPatientBloodType = new javax.swing.JLabel();
        lblPatientAllergies = new javax.swing.JLabel();
        btnViewDiagnosticResult = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cases Details");
        setModal(true);
        setName("cases"); // NOI18N
        setPreferredSize(new java.awt.Dimension(560, 760));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCaseHeader.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCaseHeader.setText("lblCaseHeader");
        getContentPane().add(lblCaseHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 26));

        lblCaseMeta.setForeground(new java.awt.Color(102, 102, 102));
        lblCaseMeta.setText("lblCaseMeta");
        getContentPane().add(lblCaseMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 48, 400, 18));

        lblCaseStatusBadge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCaseStatusBadge.setText("lblCaseStatusBadge");
        getContentPane().add(lblCaseStatusBadge, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 100, 18));

        lblSummaryHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSummaryHeader.setText("Case Summary: ");
        getContentPane().add(lblSummaryHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 166, 300, 18));

        txtCaseSummary.setColumns(20);
        txtCaseSummary.setLineWrap(true);
        txtCaseSummary.setRows(5);
        txtCaseSummary.setWrapStyleWord(true);
        scrCaseSummary.setViewportView(txtCaseSummary);

        getContentPane().add(scrCaseSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 186, 520, 66));

        btnSaveSummary.setBackground(new java.awt.Color(38, 117, 154));
        btnSaveSummary.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveSummary.setText("Save Summary");
        btnSaveSummary.addActionListener(this::btnSaveSummary);
        getContentPane().add(btnSaveSummary, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 258, 140, 26));

        lblDiagnosticsHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDiagnosticsHeader.setText("Diagnostic Requests: ");
        getContentPane().add(lblDiagnosticsHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 476, 300, 18));

        tblCaseConsultations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Doctor", "Complaint", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCaseConsultations.getTableHeader().setReorderingAllowed(false);
        scrCaseConsultations.setViewportView(tblCaseConsultations);
        tblCaseConsultations.getAccessibleContext().setAccessibleName("");

        getContentPane().add(scrCaseConsultations, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 312, 520, 120));

        lblConsultationsHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConsultationsHeader.setText("Consultations: ");
        getContentPane().add(lblConsultationsHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 292, 300, 18));

        tblCaseDiagnostics.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Service", "Requested Date", "Status", "Result Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCaseDiagnostics.getTableHeader().setReorderingAllowed(false);
        scrCaseDiagnostics.setViewportView(tblCaseDiagnostics);

        getContentPane().add(scrCaseDiagnostics, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 496, 520, 120));

        btnViewConsultation.setText("View Details");
        btnViewConsultation.addActionListener(this::btnViewConsultation);
        getContentPane().add(btnViewConsultation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 438, 160, 30));

        btnCloseCase.setBackground(new java.awt.Color(38, 117, 154));
        btnCloseCase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCloseCase.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseCase.setText("Close Case");
        btnCloseCase.addActionListener(this::btnCloseCase);
        getContentPane().add(btnCloseCase, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 668, 250, 36));

        lblCaseRoleNote.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblCaseRoleNote.setForeground(new java.awt.Color(102, 102, 102));
        lblCaseRoleNote.setText("lblCaseRoleNote");
        getContentPane().add(lblCaseRoleNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 68, 500, 18));

        lblPatientInfoHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPatientInfoHeader.setText("Patient Information: ");
        getContentPane().add(lblPatientInfoHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 92, 200, 18));

        lblPatientAge.setText("Age: ");
        getContentPane().add(lblPatientAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 112, 90, 20));

        lblPatientGender.setText("Gender: ");
        getContentPane().add(lblPatientGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 112, 110, 20));

        lblPatientBloodType.setText("Blood Type: ");
        getContentPane().add(lblPatientBloodType, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 112, 120, 20));

        lblPatientAllergies.setText("Allergies: ");
        getContentPane().add(lblPatientAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 134, 520, 20));

        btnViewDiagnosticResult.setText("View Result");
        btnViewDiagnosticResult.addActionListener(this::btnViewDiagnosticResult);
        getContentPane().add(btnViewDiagnosticResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 622, 160, 30));

        btnCancel.setBackground(new java.awt.Color(38, 117, 154));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancel);
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 668, 250, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveSummary(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSummary
        String result = doctor.saveCaseSummary(txtCaseSummary.getText());
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        JOptionPane.showMessageDialog(this, "Case summary saved.");
        doctor.loadCase(caseId);
        refresh();
    }//GEN-LAST:event_btnSaveSummary

    private void btnViewConsultation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewConsultation
        int row = tblCaseConsultations.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a consultation.");
            return;
        }
        int consultId = doctor.getCaseConsultId(row);
        if (consultId < 0) {
            return;
        }
        ConsultationsDialog dialog = new ConsultationsDialog((java.awt.Frame) getOwner(), true, doctor, consultId);
        dialog.setVisible(true);
        doctor.loadCase(caseId);
        refresh();
    }//GEN-LAST:event_btnViewConsultation

    private void btnViewDiagnosticResult(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDiagnosticResult
        int row = tblCaseDiagnostics.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a diagnostic request.");
            return;
        }
        JOptionPane.showMessageDialog(this, doctor.getCaseTestDetail(row), "Diagnostic Result", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewDiagnosticResult

    private void btnCloseCase(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseCase
        int confirm = JOptionPane.showConfirmDialog(this, "Close this case? This cannot be undone.",
                "Confirm Close", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        String result = doctor.closeCase();
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        JOptionPane.showMessageDialog(this, "Case closed.");
        doctor.loadCase(caseId);
        refresh();
    }//GEN-LAST:event_btnCloseCase

    private void btnCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel
        dispose();
    }//GEN-LAST:event_btnCancel


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                CasesDialog dialog = new CasesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCloseCase;
    private javax.swing.JButton btnSaveSummary;
    private javax.swing.JButton btnViewConsultation;
    private javax.swing.JButton btnViewDiagnosticResult;
    private javax.swing.JLabel lblCaseHeader;
    private javax.swing.JLabel lblCaseMeta;
    private javax.swing.JLabel lblCaseRoleNote;
    private javax.swing.JLabel lblCaseStatusBadge;
    private javax.swing.JLabel lblConsultationsHeader;
    private javax.swing.JLabel lblDiagnosticsHeader;
    private javax.swing.JLabel lblPatientAge;
    private javax.swing.JLabel lblPatientAllergies;
    private javax.swing.JLabel lblPatientBloodType;
    private javax.swing.JLabel lblPatientGender;
    private javax.swing.JLabel lblPatientInfoHeader;
    private javax.swing.JLabel lblSummaryHeader;
    private javax.swing.JScrollPane scrCaseConsultations;
    private javax.swing.JScrollPane scrCaseDiagnostics;
    private javax.swing.JScrollPane scrCaseSummary;
    private javax.swing.JTable tblCaseConsultations;
    private javax.swing.JTable tblCaseDiagnostics;
    private javax.swing.JTextArea txtCaseSummary;
    // End of variables declaration//GEN-END:variables
}
