/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Doctor;

import javax.swing.JOptionPane;

/**
 *
 * @author Sascha
 */
public class ConsultationsDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultationsDialog.class.getName());

    private DoctorServices doctor;
    private int consultId = -1;
    private static final String[] STATUS_OPTIONS = {"booked", "completed", "cancelled"};

    /**
     * Creates new form ConsultationDialog
     */
    public ConsultationsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    // Used by the doctor dashboard to open one specific consultation
    public ConsultationsDialog(java.awt.Frame parent, boolean modal, DoctorServices doctor, int consultId) {
        super(parent, modal);
        initComponents();
        this.doctor = doctor;
        this.consultId = consultId;

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Booked", "Completed", "Cancelled"}));

        if (!doctor.loadConsultation(consultId)) {
            JOptionPane.showMessageDialog(this, "This consultation could not be found.");
            dispose();
            return;
        }
        refresh();
    }

    // Redraws every field from the doctor object's current data
    private void refresh() {
        lblConsultHeader.setText(doctor.getConsultTitle());
        lblConsultMeta.setText(doctor.getConsultMeta());
        lblConsultStatusBadge.setText(doctor.getConsultStatus());
        lblConsultRoleNote.setText(doctor.getConsultRoleNote());
        lblPrescriptionStatus.setText(doctor.getPrescriptionStatus(consultId));
        lblDiagnosticStatus.setText(doctor.getDiagnosticStatus(consultId));

        txtComplaint.setText(doctor.getComplaint());
        txtComplaint.setEditable(false);
        txtVitalSigns.setText(doctor.getVitalSigns());
        txtNotes.setText(doctor.getNotes());

        for (int i = 0; i < STATUS_OPTIONS.length; i++) {
            if (STATUS_OPTIONS[i].equals(doctor.getConsultStatus().toLowerCase())) {
                cmbStatus.setSelectedIndex(i);
            }
        }

        boolean canEdit = doctor.canEditConsultation();
        txtVitalSigns.setEditable(canEdit);
        txtNotes.setEditable(canEdit);
        cmbStatus.setEnabled(canEdit);
        btnSaveConsultation.setEnabled(canEdit);
        btnWritePrescription.setEnabled(canEdit);
        btnRequestDiagnostic.setEnabled(canEdit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConsultHeader = new javax.swing.JLabel();
        lblConsultMeta = new javax.swing.JLabel();
        lblConsultStatusBadge = new javax.swing.JLabel();
        lblConsultRoleNote = new javax.swing.JLabel();
        lblComplaintHeader = new javax.swing.JLabel();
        scrComplaint = new javax.swing.JScrollPane();
        txtComplaint = new javax.swing.JTextArea();
        lblVitalsHeader = new javax.swing.JLabel();
        scrVitalSigns = new javax.swing.JScrollPane();
        txtVitalSigns = new javax.swing.JTextArea();
        lblNotesHeader = new javax.swing.JLabel();
        scrNotes = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        lblStatusHeader = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        btnWritePrescription = new javax.swing.JButton();
        btnRequestDiagnostic = new javax.swing.JButton();
        lblPrescriptionStatus = new javax.swing.JLabel();
        lblDiagnosticStatus = new javax.swing.JLabel();
        btnSaveConsultation = new javax.swing.JButton();
        btnCloseDialog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultation Notes");
        setModal(true);
        setName("consultations"); // NOI18N
        setPreferredSize(new java.awt.Dimension(560, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConsultHeader.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblConsultHeader.setText("lblConsultHeader");
        getContentPane().add(lblConsultHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 26));

        lblConsultMeta.setForeground(new java.awt.Color(102, 102, 102));
        lblConsultMeta.setText("lblConsultMeta");
        getContentPane().add(lblConsultMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 48, 400, 18));

        lblConsultStatusBadge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConsultStatusBadge.setText("lblConsultStatusBadge");
        getContentPane().add(lblConsultStatusBadge, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 100, 18));

        lblConsultRoleNote.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblConsultRoleNote.setForeground(new java.awt.Color(102, 102, 102));
        lblConsultRoleNote.setText("lblConsultRoleNote");
        getContentPane().add(lblConsultRoleNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 68, 520, 18));

        lblComplaintHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComplaintHeader.setText("Complaint:");
        getContentPane().add(lblComplaintHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 96, 300, 18));

        txtComplaint.setColumns(20);
        txtComplaint.setLineWrap(true);
        txtComplaint.setRows(2);
        txtComplaint.setWrapStyleWord(true);
        scrComplaint.setViewportView(txtComplaint);

        getContentPane().add(scrComplaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 116, 520, 50));

        lblVitalsHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVitalsHeader.setText("Vital Signs: ");
        getContentPane().add(lblVitalsHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 176, 300, 18));

        txtVitalSigns.setColumns(20);
        txtVitalSigns.setLineWrap(true);
        txtVitalSigns.setRows(2);
        txtVitalSigns.setWrapStyleWord(true);
        scrVitalSigns.setViewportView(txtVitalSigns);

        getContentPane().add(scrVitalSigns, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 196, 520, 50));

        lblNotesHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNotesHeader.setText("Notes: ");
        getContentPane().add(lblNotesHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 256, 300, 18));

        txtNotes.setColumns(20);
        txtNotes.setLineWrap(true);
        txtNotes.setRows(5);
        txtNotes.setWrapStyleWord(true);
        scrNotes.setViewportView(txtNotes);

        getContentPane().add(scrNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 276, 520, 110));

        lblStatusHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStatusHeader.setText("Status: ");
        getContentPane().add(lblStatusHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 396, 180, 18));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 416, 180, 28));

        btnWritePrescription.setBackground(new java.awt.Color(38, 117, 154));
        btnWritePrescription.setForeground(new java.awt.Color(255, 255, 255));
        btnWritePrescription.setText("Write Prescription");
        btnWritePrescription.setFocusPainted(false);
        btnWritePrescription.addActionListener(this::btnWritePrescription);
        getContentPane().add(btnWritePrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 416, 160, 28));

        btnRequestDiagnostic.setBackground(new java.awt.Color(38, 117, 154));
        btnRequestDiagnostic.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestDiagnostic.setText("Request Diagnostic Test");
        btnRequestDiagnostic.setFocusPainted(false);
        btnRequestDiagnostic.addActionListener(this::btnRequestDiagnostic);
        getContentPane().add(btnRequestDiagnostic, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 416, 160, 28));

        lblPrescriptionStatus.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblPrescriptionStatus.setForeground(new java.awt.Color(102, 102, 102));
        lblPrescriptionStatus.setText("lblPrescriptionStatus");
        getContentPane().add(lblPrescriptionStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 452, 520, 18));

        lblDiagnosticStatus.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblDiagnosticStatus.setForeground(new java.awt.Color(102, 102, 102));
        lblDiagnosticStatus.setText("lblDiagnosticStatus");
        getContentPane().add(lblDiagnosticStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 472, 520, 18));

        btnSaveConsultation.setBackground(new java.awt.Color(38, 117, 154));
        btnSaveConsultation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSaveConsultation.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveConsultation.setText("Save Changes");
        btnSaveConsultation.addActionListener(this::btnSaveConsultation);
        getContentPane().add(btnSaveConsultation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 250, 36));

        btnCloseDialog.setBackground(new java.awt.Color(38, 117, 154));
        btnCloseDialog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCloseDialog.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseDialog.setText("Close Page");
        btnCloseDialog.addActionListener(this::btnCloseDialog);
        getContentPane().add(btnCloseDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 520, 250, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveConsultation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveConsultation
        int statusIndex = cmbStatus.getSelectedIndex();
        String status = STATUS_OPTIONS[statusIndex < 0 ? 0 : statusIndex];

        String result = doctor.saveConsultation(txtVitalSigns.getText(), txtNotes.getText(), status);
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        JOptionPane.showMessageDialog(this, "Consultation updated.");
        doctor.loadConsultation(consultId);
        refresh();
    }//GEN-LAST:event_btnSaveConsultation

    private void btnWritePrescription(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWritePrescription
        if (!doctor.canEditConsultation()) {
            JOptionPane.showMessageDialog(this, "You cannot write a prescription for this consultation.");
            return;
        }
        PrescriptionDialog dialog = new PrescriptionDialog((java.awt.Frame) getOwner(), true, doctor, consultId);
        dialog.setVisible(true);
        doctor.loadConsultation(consultId);
        refresh();
    }//GEN-LAST:event_btnWritePrescription

    private void btnRequestDiagnostic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestDiagnostic
        if (!doctor.canEditConsultation()) {
            JOptionPane.showMessageDialog(this, "You cannot request diagnostic services for this consultation.");
            return;
        }
        DiagnosticRequestDialog dialog = new DiagnosticRequestDialog((java.awt.Frame) getOwner(), true, doctor, consultId);
        dialog.setVisible(true);
        doctor.loadConsultation(consultId);
        refresh();
    }//GEN-LAST:event_btnRequestDiagnostic

    private void btnCloseDialog(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseDialog
        dispose();
    }//GEN-LAST:event_btnCloseDialog

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ConsultationsDialog dialog = new ConsultationsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseDialog;
    private javax.swing.JButton btnRequestDiagnostic;
    private javax.swing.JButton btnSaveConsultation;
    private javax.swing.JButton btnWritePrescription;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel lblComplaintHeader;
    private javax.swing.JLabel lblConsultHeader;
    private javax.swing.JLabel lblConsultMeta;
    private javax.swing.JLabel lblConsultRoleNote;
    private javax.swing.JLabel lblConsultStatusBadge;
    private javax.swing.JLabel lblDiagnosticStatus;
    private javax.swing.JLabel lblNotesHeader;
    private javax.swing.JLabel lblPrescriptionStatus;
    private javax.swing.JLabel lblStatusHeader;
    private javax.swing.JLabel lblVitalsHeader;
    private javax.swing.JScrollPane scrComplaint;
    private javax.swing.JScrollPane scrNotes;
    private javax.swing.JScrollPane scrVitalSigns;
    private javax.swing.JTextArea txtComplaint;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextArea txtVitalSigns;
    // End of variables declaration//GEN-END:variables
}
