/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Doctor;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sascha
 */
public class ConsultationsDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConsultationsDialog.class.getName());

    private DoctorServices doctor;
    private int consultId = -1;

    /**
     * Creates new form ConsultationDialog
     */
    public ConsultationsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    // Used by the doctor dashboard to open one specific consultation
    public ConsultationsDialog(java.awt.Frame parent, boolean modal, DoctorServices doctor, int consultId) {
        super(parent, modal);
        initComponents();
        this.doctor = doctor;
        this.consultId = consultId;

        if (!doctor.loadConsultation(consultId)) {
            JOptionPane.showMessageDialog(this, "This consultation could not be found.");
            dispose();
            return;
        }
        refresh();
    }

    // Redraws every field from the doctor object's current data
    private void refresh() {
        lblConsultHeader.setText(doctor.getConsultTitle());
        lblConsultMeta.setText(doctor.getConsultMeta());
        lblConsultStatusBadge.setText(doctor.getConsultStatus());
        lblConsultRoleNote.setText("<html>" + doctor.getConsultRoleNote() + "</html>");

        txtComplaint.setText(doctor.getComplaint());
        txtComplaint.setEditable(false);
        txtVitalSigns.setText(doctor.getVitalSigns());
        txtNotes.setText(doctor.getNotes());

        boolean canEdit = doctor.canEditConsultation();
        txtVitalSigns.setEditable(canEdit);
        txtNotes.setEditable(canEdit);
        btnCompleteConsultation.setEnabled(canEdit);
        btnWritePrescription.setEnabled(canEdit);
        btnRequestDiagnostic.setEnabled(canEdit);

        ArrayList<String[]> items = doctor.getPrescriptionItems(consultId);
        DefaultTableModel prescriptionModel = (DefaultTableModel) tblPrescriptionItemsView.getModel();
        prescriptionModel.setRowCount(0);
        for (String[] item : items) {
            prescriptionModel.addRow(new Object[]{item[1], item[2], item[3], item[4]});
        }
        btnWritePrescription.setText(items.isEmpty() ? "Write Prescription" : "Edit Prescription");

        ArrayList<Object[]> requests = doctor.getDiagnosticRequests(consultId);
        DefaultTableModel diagnosticModel = (DefaultTableModel) tblDiagnosticRequestsView.getModel();
        diagnosticModel.setRowCount(0);
        for (Object[] row : requests) {
            diagnosticModel.addRow(row);
        }
        btnDeleteDiagnosticRequest.setEnabled(canEdit && !requests.isEmpty());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConsultHeader = new javax.swing.JLabel();
        lblConsultStatusBadge = new javax.swing.JLabel();
        lblConsultMeta = new javax.swing.JLabel();
        lblConsultRoleNote = new javax.swing.JLabel();
        btnViewCase = new javax.swing.JButton();
        lblComplaintHeader = new javax.swing.JLabel();
        scrComplaint = new javax.swing.JScrollPane();
        txtComplaint = new javax.swing.JTextArea();
        lblVitalsHeader = new javax.swing.JLabel();
        scrVitalSigns = new javax.swing.JScrollPane();
        txtVitalSigns = new javax.swing.JTextArea();
        lblNotesHeader = new javax.swing.JLabel();
        scrNotes = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();
        lblPrescriptionHeader = new javax.swing.JLabel();
        btnWritePrescription = new javax.swing.JButton();
        scrPrescriptionItemsView = new javax.swing.JScrollPane();
        tblPrescriptionItemsView = new javax.swing.JTable();
        lblDiagnosticHeader = new javax.swing.JLabel();
        btnRequestDiagnostic = new javax.swing.JButton();
        btnDeleteDiagnosticRequest = new javax.swing.JButton();
        scrDiagnosticRequestsView = new javax.swing.JScrollPane();
        tblDiagnosticRequestsView = new javax.swing.JTable();
        btnCompleteConsultation = new javax.swing.JButton();
        btnCloseDialog = new javax.swing.JButton();
        btnSaveDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultation Notes");
        setModal(true);
        setName("consultations"); // NOI18N
        setPreferredSize(new java.awt.Dimension(560, 910));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConsultHeader.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblConsultHeader.setText("lblConsultHeader");
        getContentPane().add(lblConsultHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 26));

        lblConsultStatusBadge.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblConsultStatusBadge.setText("lblConsultStatusBadge");
        getContentPane().add(lblConsultStatusBadge, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 100, 18));

        lblConsultMeta.setForeground(new java.awt.Color(102, 102, 102));
        lblConsultMeta.setText("lblConsultMeta");
        getContentPane().add(lblConsultMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 48, 520, 18));

        lblConsultRoleNote.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblConsultRoleNote.setForeground(new java.awt.Color(102, 102, 102));
        lblConsultRoleNote.setText("lblConsultRoleNote");
        lblConsultRoleNote.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblConsultRoleNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 68, 350, 40));

        btnViewCase.setBackground(new java.awt.Color(38, 117, 154));
        btnViewCase.setForeground(new java.awt.Color(255, 255, 255));
        btnViewCase.setText("View Case");
        btnViewCase.setFocusPainted(false);
        btnViewCase.addActionListener(this::btnViewCase);
        getContentPane().add(btnViewCase, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 68, 130, 26));

        lblComplaintHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblComplaintHeader.setText("Complaint:");
        getContentPane().add(lblComplaintHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 114, 300, 18));

        txtComplaint.setColumns(20);
        txtComplaint.setLineWrap(true);
        txtComplaint.setRows(2);
        txtComplaint.setWrapStyleWord(true);
        scrComplaint.setViewportView(txtComplaint);

        getContentPane().add(scrComplaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 134, 520, 50));

        lblVitalsHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVitalsHeader.setText("Vital Signs: ");
        getContentPane().add(lblVitalsHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 194, 300, 18));

        txtVitalSigns.setColumns(20);
        txtVitalSigns.setLineWrap(true);
        txtVitalSigns.setRows(2);
        txtVitalSigns.setWrapStyleWord(true);
        scrVitalSigns.setViewportView(txtVitalSigns);

        getContentPane().add(scrVitalSigns, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 214, 520, 50));

        lblNotesHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNotesHeader.setText("Notes: ");
        getContentPane().add(lblNotesHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 274, 300, 18));

        txtNotes.setColumns(20);
        txtNotes.setLineWrap(true);
        txtNotes.setRows(5);
        txtNotes.setWrapStyleWord(true);
        scrNotes.setViewportView(txtNotes);

        getContentPane().add(scrNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 294, 520, 110));

        lblPrescriptionHeader.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblPrescriptionHeader.setText("Prescription:");
        getContentPane().add(lblPrescriptionHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 466, 140, 22));

        btnWritePrescription.setBackground(new java.awt.Color(38, 117, 154));
        btnWritePrescription.setForeground(new java.awt.Color(255, 255, 255));
        btnWritePrescription.setText("Write Prescription");
        btnWritePrescription.setFocusPainted(false);
        btnWritePrescription.addActionListener(this::btnWritePrescription);
        getContentPane().add(btnWritePrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, 200, 26));

        tblPrescriptionItemsView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug", "Dosage", "Frequency", "Days"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrescriptionItemsView.getTableHeader().setReorderingAllowed(false);
        scrPrescriptionItemsView.setViewportView(tblPrescriptionItemsView);

        getContentPane().add(scrPrescriptionItemsView, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 494, 520, 86));

        lblDiagnosticHeader.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblDiagnosticHeader.setText("Diagnostic Requests:");
        getContentPane().add(lblDiagnosticHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 626, 170, 22));

        btnRequestDiagnostic.setBackground(new java.awt.Color(38, 117, 154));
        btnRequestDiagnostic.setForeground(new java.awt.Color(255, 255, 255));
        btnRequestDiagnostic.setText("Add Request");
        btnRequestDiagnostic.setFocusPainted(false);
        btnRequestDiagnostic.addActionListener(this::btnRequestDiagnostic);
        getContentPane().add(btnRequestDiagnostic, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 778, 200, 26));

        btnDeleteDiagnosticRequest.setText("Delete Selected");
        btnDeleteDiagnosticRequest.setFocusPainted(false);
        btnDeleteDiagnosticRequest.addActionListener(this::btnDeleteDiagnosticRequest);
        getContentPane().add(btnDeleteDiagnosticRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 778, 200, 26));

        tblDiagnosticRequestsView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Service", "Requested Date", "Status", "Result Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDiagnosticRequestsView.getTableHeader().setReorderingAllowed(false);
        tblDiagnosticRequestsView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDiagnosticRequestsView(evt);
            }
        });
        scrDiagnosticRequestsView.setViewportView(tblDiagnosticRequestsView);

        getContentPane().add(scrDiagnosticRequestsView, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 658, 520, 110));

        btnCompleteConsultation.setBackground(new java.awt.Color(38, 117, 154));
        btnCompleteConsultation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCompleteConsultation.setForeground(new java.awt.Color(255, 255, 255));
        btnCompleteConsultation.setText("Complete Consultation");
        btnCompleteConsultation.addActionListener(this::btnCompleteConsultation);
        getContentPane().add(btnCompleteConsultation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 830, 250, 36));

        btnCloseDialog.setBackground(new java.awt.Color(38, 117, 154));
        btnCloseDialog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCloseDialog.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseDialog.setText("Cancel");
        btnCloseDialog.addActionListener(this::btnCloseDialog);
        getContentPane().add(btnCloseDialog, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 830, 250, 36));

        btnSaveDetails.setBackground(new java.awt.Color(38, 117, 154));
        btnSaveDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveDetails.setText("Save Details");
        btnSaveDetails.addActionListener(this::btnSaveDetails);
        getContentPane().add(btnSaveDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 414, 140, 26));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompleteConsultation(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteConsultation
        String result = doctor.saveConsultation(txtVitalSigns.getText(), txtNotes.getText());
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        JOptionPane.showMessageDialog(this, "Consultation updated.");
        doctor.loadConsultation(consultId);
        refresh();
    }//GEN-LAST:event_btnCompleteConsultation

    private void btnWritePrescription(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWritePrescription
        if (!doctor.canEditConsultation()) {
            JOptionPane.showMessageDialog(this, "You cannot write a prescription for this consultation.");
            return;
        }
        PrescriptionDialog dialog = new PrescriptionDialog((java.awt.Frame) getOwner(), true, doctor, consultId);
        dialog.setVisible(true);
        doctor.loadConsultation(consultId);
        refresh();
    }//GEN-LAST:event_btnWritePrescription

    private void btnRequestDiagnostic(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestDiagnostic
        if (!doctor.canEditConsultation()) {
            JOptionPane.showMessageDialog(this, "You cannot request diagnostic services for this consultation.");
            return;
        }
        DiagnosticRequestDialog dialog = new DiagnosticRequestDialog((java.awt.Frame) getOwner(), true, doctor, consultId);
        dialog.setVisible(true);
        doctor.loadConsultation(consultId);
        refresh();
    }//GEN-LAST:event_btnRequestDiagnostic

    private void btnDeleteDiagnosticRequest(java.awt.event.ActionEvent evt) {
        int row = tblDiagnosticRequestsView.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a diagnostic request to delete.");
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Delete this diagnostic request?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        String result = doctor.deleteDiagnosticRequest(doctor.getDiagnosticRequestId(row));
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        refresh();
    }

    private void tblDiagnosticRequestsView(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() != 2) {
            return;
        }
        int row = tblDiagnosticRequestsView.getSelectedRow();
        if (row < 0) {
            return;
        }
        JOptionPane.showMessageDialog(this, doctor.getDiagnosticRequestDetail(row), "Diagnostic Result", JOptionPane.INFORMATION_MESSAGE);
    }

    private void btnViewCase(java.awt.event.ActionEvent evt) {
        int caseId = doctor.getConsultCaseId();
        if (caseId < 0) {
            return;
        }
        CasesDialog dialog = new CasesDialog((java.awt.Frame) getOwner(), true, doctor, caseId);
        dialog.setVisible(true);
        doctor.loadConsultation(consultId);
        refresh();
    }

    private void btnCloseDialog(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseDialog
        dispose();
    }//GEN-LAST:event_btnCloseDialog

    private void btnSaveDetails(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDetails
        String result = doctor.saveCaseSummary(txtCaseSummary.getText());
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        JOptionPane.showMessageDialog(this, "Case summary saved.");
        doctor.loadCase(caseId);
        refresh();
    }//GEN-LAST:event_btnSaveDetails


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ConsultationsDialog dialog = new ConsultationsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseDialog;
    private javax.swing.JButton btnCompleteConsultation;
    private javax.swing.JButton btnDeleteDiagnosticRequest;
    private javax.swing.JButton btnRequestDiagnostic;
    private javax.swing.JButton btnSaveDetails;
    private javax.swing.JButton btnViewCase;
    private javax.swing.JButton btnWritePrescription;
    private javax.swing.JLabel lblComplaintHeader;
    private javax.swing.JLabel lblConsultHeader;
    private javax.swing.JLabel lblConsultMeta;
    private javax.swing.JLabel lblConsultRoleNote;
    private javax.swing.JLabel lblConsultStatusBadge;
    private javax.swing.JLabel lblDiagnosticHeader;
    private javax.swing.JLabel lblNotesHeader;
    private javax.swing.JLabel lblPrescriptionHeader;
    private javax.swing.JLabel lblVitalsHeader;
    private javax.swing.JScrollPane scrComplaint;
    private javax.swing.JScrollPane scrDiagnosticRequestsView;
    private javax.swing.JScrollPane scrNotes;
    private javax.swing.JScrollPane scrPrescriptionItemsView;
    private javax.swing.JScrollPane scrVitalSigns;
    private javax.swing.JTable tblDiagnosticRequestsView;
    private javax.swing.JTable tblPrescriptionItemsView;
    private javax.swing.JTextArea txtComplaint;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextArea txtVitalSigns;
    // End of variables declaration//GEN-END:variables
}
