/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Doctor;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sascha
 */
public class DiagnosticRequestDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DiagnosticRequestDialog.class.getName());

    private DoctorServices doctor;
    // requests already added to the request list being built: {serviceId, serviceName, category, type, remarks}
    private ArrayList<String[]> pendingRequests = new ArrayList<>();
    private int selectedServiceId = -1;
    private String selectedServiceName = "";
    private String selectedCategory = "";
    private String selectedType = "";

    // Nothing is written to file from this dialog. The caller (ConsultationsDialog) only
    // submits these requests when its own "Save Progress"/"Complete Consultation" is clicked.
    private boolean saved = false;
    private ArrayList<String[]> resultRequests = new ArrayList<>();

    /**
     * Creates new form DiagnosticRequestDialog
     */
    public DiagnosticRequestDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    // Used by the Consultation dialog to request diagnostic services for one consultation
    public DiagnosticRequestDialog(java.awt.Frame parent, boolean modal, DoctorServices doctor, int consultId) {
        super(parent, modal);
        initComponents();
        this.doctor = doctor;

        lblDiagHeader.setText("Request Diagnostic Service");
        lblDiagMeta.setText("Consultation #" + consultId);
        txtServiceSearch.setText("");
        txtRemarks.setText("");

        ArrayList<String> categories = doctor.getServiceCategories();
        cmbCategoryFilter.setModel(new javax.swing.DefaultComboBoxModel<>(categories.toArray(new String[0])));
        loadTypesForCategory();

        if (!doctor.canEditConsultation()) {
            lblSelectedService.setText("You cannot request diagnostic services for this consultation.");
            setInputsEnabled(false);
        } else {
            searchServices();
        }
    }

    // true once the doctor clicked "Submit Requests" in this dialog
    public boolean isSaved() {
        return saved;
    }

    // the drafted requests as {serviceId, serviceName, remarks}, only meaningful when isSaved() is true
    public ArrayList<String[]> getResultRequests() {
        ArrayList<String[]> result = new ArrayList<>();
        for (String[] r : resultRequests) {
            result.add(new String[]{r[0], r[1], r[4]});
        }
        return result;
    }

    private void setInputsEnabled(boolean enabled) {
        cmbCategoryFilter.setEnabled(enabled);
        cmbTypeFilter.setEnabled(enabled);
        txtServiceSearch.setEnabled(enabled);
        tblServiceResults.setEnabled(enabled);
        txtRemarks.setEnabled(enabled);
        btnAddRequest.setEnabled(enabled);
        btnRemoveRequest.setEnabled(enabled);
        btnSubmitRequests.setEnabled(enabled);
    }

    private void loadTypesForCategory() {
        String category = "All";
        if (cmbCategoryFilter.getSelectedItem() != null) {
            category = cmbCategoryFilter.getSelectedItem().toString();
        }
        ArrayList<String> types = doctor.getServiceTypes(category);
        cmbTypeFilter.setModel(new javax.swing.DefaultComboBoxModel<>(types.toArray(new String[0])));
    }

    private void searchServices() {
        String category = "All";
        if (cmbCategoryFilter.getSelectedItem() != null) {
            category = cmbCategoryFilter.getSelectedItem().toString();
        }
        String type = "All";
        if (cmbTypeFilter.getSelectedItem() != null) {
            type = cmbTypeFilter.getSelectedItem().toString();
        }
        DefaultTableModel model = (DefaultTableModel) tblServiceResults.getModel();
        model.setRowCount(0);
        for (Object[] row : doctor.searchServices(category, type, txtServiceSearch.getText())) {
            model.addRow(row);
        }
    }

    private void refreshRequestsTable() {
        DefaultTableModel model = (DefaultTableModel) tblRequestList.getModel();
        model.setRowCount(0);
        for (String[] request : pendingRequests) {
            model.addRow(new Object[]{request[1], request[2], request[3], request[4]});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDiagHeader = new javax.swing.JLabel();
        lblDiagMeta = new javax.swing.JLabel();
        lblDiagFilterHeader = new javax.swing.JLabel();
        cmbCategoryFilter = new javax.swing.JComboBox<>();
        cmbTypeFilter = new javax.swing.JComboBox<>();
        txtServiceSearch = new javax.swing.JTextField();
        lblSelectedService = new javax.swing.JLabel();
        scrServiceResults = new javax.swing.JScrollPane();
        tblServiceResults = new javax.swing.JTable();
        lblRemarksHeader = new javax.swing.JLabel();
        scrRemarks = new javax.swing.JScrollPane();
        txtRemarks = new javax.swing.JTextArea();
        btnAddRequest = new javax.swing.JButton();
        lblRequestsHeader = new javax.swing.JLabel();
        scrRequestList = new javax.swing.JScrollPane();
        tblRequestList = new javax.swing.JTable();
        btnRemoveRequest = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSubmitRequests = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Request Diagnostic Service");
        setModal(true);
        setPreferredSize(new java.awt.Dimension(560, 785));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDiagHeader.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblDiagHeader.setText("lblDiagHeader");
        getContentPane().add(lblDiagHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 26));

        lblDiagMeta.setForeground(new java.awt.Color(102, 102, 102));
        lblDiagMeta.setText("lblDiagMeta");
        getContentPane().add(lblDiagMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 48, 400, 18));

        lblDiagFilterHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDiagFilterHeader.setText("Select Service: ");
        getContentPane().add(lblDiagFilterHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, 300, 18));

        cmbCategoryFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCategoryFilter.addActionListener(this::cmbCategoryFilter);
        getContentPane().add(cmbCategoryFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 98, 170, 26));

        cmbTypeFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTypeFilter.addActionListener(this::cmbTypeFilter);
        getContentPane().add(cmbTypeFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 98, 200, 26));

        txtServiceSearch.setText("Search service...");
        txtServiceSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtServiceSearch(evt);
            }
        });
        getContentPane().add(txtServiceSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 134, 520, 26));

        lblSelectedService.setForeground(new java.awt.Color(102, 102, 102));
        lblSelectedService.setText("Selected: —");
        getContentPane().add(lblSelectedService, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 520, 18));

        tblServiceResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Service Name", "Category", "Type", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblServiceResults.setColumnSelectionAllowed(true);
        tblServiceResults.setSelectionBackground(new java.awt.Color(38, 117, 154));
        tblServiceResults.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblServiceResults.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblServiceResults.getTableHeader().setReorderingAllowed(false);
        tblServiceResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblServiceResults(evt);
            }
        });
        scrServiceResults.setViewportView(tblServiceResults);
        tblServiceResults.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(scrServiceResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 520, 140));

        lblRemarksHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRemarksHeader.setText("Request Remarks: ");
        getContentPane().add(lblRemarksHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 348, 300, 18));

        txtRemarks.setColumns(20);
        txtRemarks.setLineWrap(true);
        txtRemarks.setRows(4);
        txtRemarks.setWrapStyleWord(true);
        scrRemarks.setViewportView(txtRemarks);

        getContentPane().add(scrRemarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 368, 520, 60));

        btnAddRequest.setBackground(new java.awt.Color(38, 117, 154));
        btnAddRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnAddRequest.setText("+ Add to Request List");
        btnAddRequest.setFocusPainted(false);
        btnAddRequest.addActionListener(this::btnAddRequest);
        getContentPane().add(btnAddRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 520, 30));

        lblRequestsHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRequestsHeader.setText("Pending Requests: ");
        getContentPane().add(lblRequestsHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 300, 18));

        tblRequestList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Service", "Category", "Type", "Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblRequestList.setColumnSelectionAllowed(true);
        tblRequestList.setSelectionBackground(new java.awt.Color(38, 117, 154));
        tblRequestList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblRequestList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblRequestList.getTableHeader().setReorderingAllowed(false);
        scrRequestList.setViewportView(tblRequestList);
        tblRequestList.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(scrRequestList, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 520, 130));

        btnRemoveRequest.setText("Remove Selected");
        btnRemoveRequest.setFocusPainted(false);
        btnRemoveRequest.addActionListener(this::btnRemoveRequest);
        getContentPane().add(btnRemoveRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 644, 250, 32));

        btnCancel.setBackground(new java.awt.Color(38, 117, 154));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancel);
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 698, 250, 36));

        btnSubmitRequests.setBackground(new java.awt.Color(38, 117, 154));
        btnSubmitRequests.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubmitRequests.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitRequests.setText("Submit Requests");
        btnSubmitRequests.addActionListener(this::btnSubmitRequests);
        getContentPane().add(btnSubmitRequests, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 698, 250, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCategoryFilter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoryFilter
        loadTypesForCategory();
        searchServices();
    }//GEN-LAST:event_cmbCategoryFilter

    private void cmbTypeFilter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTypeFilter
        searchServices();
    }//GEN-LAST:event_cmbTypeFilter

    private void btnAddRequest(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRequest
        if (selectedServiceId < 0) {
            JOptionPane.showMessageDialog(this, "Please select a service from the results above.");
            return;
        }
        String remarks = txtRemarks.getText();
        String error = doctor.checkText(remarks);
        if (error != null) {
            JOptionPane.showMessageDialog(this, error);
            return;
        }
        pendingRequests.add(new String[]{String.valueOf(selectedServiceId), selectedServiceName,
            selectedCategory, selectedType, remarks.trim()});
        refreshRequestsTable();
        txtRemarks.setText("");
    }//GEN-LAST:event_btnAddRequest

    private void btnRemoveRequest(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveRequest
        int row = tblRequestList.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a request to remove.");
            return;
        }
        pendingRequests.remove(row);
        refreshRequestsTable();
    }//GEN-LAST:event_btnRemoveRequest

    private void btnSubmitRequests(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRequests
        if (pendingRequests.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please add at least one service to the request list.");
            return;
        }
        resultRequests = pendingRequests;
        saved = true;
        dispose();
    }//GEN-LAST:event_btnSubmitRequests

    private void btnCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel
        dispose();
    }//GEN-LAST:event_btnCancel

    private void txtServiceSearch(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServiceSearch
        searchServices();
    }//GEN-LAST:event_txtServiceSearch

    private void tblServiceResults(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblServiceResults
        int row = tblServiceResults.getSelectedRow();
        if (row < 0) {
            return;
        }
        selectedServiceId = doctor.getServiceResultId(row);
        selectedServiceName = tblServiceResults.getValueAt(row, 0).toString();
        selectedCategory = tblServiceResults.getValueAt(row, 1).toString();
        selectedType = tblServiceResults.getValueAt(row, 2).toString();
        lblSelectedService.setText("Selected: " + selectedServiceName);
    }//GEN-LAST:event_tblServiceResults



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DiagnosticRequestDialog dialog = new DiagnosticRequestDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRequest;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemoveRequest;
    private javax.swing.JButton btnSubmitRequests;
    private javax.swing.JComboBox<String> cmbCategoryFilter;
    private javax.swing.JComboBox<String> cmbTypeFilter;
    private javax.swing.JLabel lblDiagFilterHeader;
    private javax.swing.JLabel lblDiagHeader;
    private javax.swing.JLabel lblDiagMeta;
    private javax.swing.JLabel lblRemarksHeader;
    private javax.swing.JLabel lblRequestsHeader;
    private javax.swing.JLabel lblSelectedService;
    private javax.swing.JScrollPane scrRemarks;
    private javax.swing.JScrollPane scrRequestList;
    private javax.swing.JScrollPane scrServiceResults;
    private javax.swing.JTable tblRequestList;
    private javax.swing.JTable tblServiceResults;
    private javax.swing.JTextArea txtRemarks;
    private javax.swing.JTextField txtServiceSearch;
    // End of variables declaration//GEN-END:variables
}
