/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Doctor;

/**
 *
 * @author Sascha
 */
public class DoctorDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DoctorDashboard.class.getName());

    /**
     * Creates new form PatientDashboard
     */
    public DoctorDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        lblPortalTitle = new javax.swing.JLabel();
        pnlNav = new javax.swing.JPanel();
        btnLogout = new javax.swing.JButton();
        btnNavConsultations1 = new javax.swing.JButton();
        btnNavSchedule1 = new javax.swing.JButton();
        btnNavCases1 = new javax.swing.JButton();
        btnNavReviews1 = new javax.swing.JButton();
        btnNavProfile1 = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        pnlProfile = new javax.swing.JPanel();
        lblProfileTitle = new javax.swing.JLabel();
        lblProfessionalHeader = new javax.swing.JLabel();
        lblContactHeader = new javax.swing.JLabel();
        lblPasswordHeader = new javax.swing.JLabel();
        lblDoctorID = new javax.swing.JLabel();
        txtDoctorID = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblDepartment = new javax.swing.JLabel();
        lblSpecialization = new javax.swing.JLabel();
        lblOffDay = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtDepartment = new javax.swing.JTextField();
        txtSpecialization = new javax.swing.JTextField();
        txtOffDay = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        lblCurrentPwd = new javax.swing.JLabel();
        pwdCurrent = new javax.swing.JPasswordField();
        lblNewPwd = new javax.swing.JLabel();
        pwdNew = new javax.swing.JPasswordField();
        lblConfirmPwd = new javax.swing.JLabel();
        pwdConfirm = new javax.swing.JPasswordField();
        lblPwdHint = new javax.swing.JLabel();
        btnSaveProfile = new javax.swing.JButton();
        btnResetProfile = new javax.swing.JButton();
        pnlCases = new javax.swing.JPanel();
        lblCasesTitle = new javax.swing.JLabel();
        scrCases = new javax.swing.JScrollPane();
        tblCases = new javax.swing.JTable();
        pnlSchedule = new javax.swing.JPanel();
        lblScheduleTitle = new javax.swing.JLabel();
        scrSchedule = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        pnlConsultations = new javax.swing.JPanel();
        lblConsultationsTitle = new javax.swing.JLabel();
        btnPrevWeek = new javax.swing.JButton();
        btnNextWeek = new javax.swing.JButton();
        lblWeekRange = new javax.swing.JLabel();
        scrCalendar = new javax.swing.JScrollPane();
        tblCalendar = new javax.swing.JTable();
        pnlReviews = new javax.swing.JPanel();
        lblReviewsTitle = new javax.swing.JLabel();
        scrReviews = new javax.swing.JScrollPane();
        tblReviews = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HMS Doctor Portal");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcome, Doctor");
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 300, 30));

        pnlHeader.setBackground(new java.awt.Color(38, 117, 154));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPortalTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPortalTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblPortalTitle.setText("APU Medical Centre - Doctor Portal");
        pnlHeader.add(lblPortalTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 450, 30));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        pnlNav.setBackground(new java.awt.Color(30, 95, 125));
        pnlNav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setBackground(new java.awt.Color(30, 95, 125));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnLogout.setFocusPainted(false);
        btnLogout.setFocusable(false);
        btnLogout.setRolloverEnabled(false);
        pnlNav.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 160, 40));

        btnNavConsultations1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNavConsultations1.setForeground(new java.awt.Color(38, 117, 154));
        btnNavConsultations1.setText("Consultations");
        btnNavConsultations1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 1));
        btnNavConsultations1.setFocusPainted(false);
        btnNavConsultations1.setFocusable(false);
        btnNavConsultations1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlNav.add(btnNavConsultations1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, 40));

        btnNavSchedule1.setBackground(new java.awt.Color(30, 95, 125));
        btnNavSchedule1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNavSchedule1.setForeground(new java.awt.Color(255, 255, 255));
        btnNavSchedule1.setText("Schedule");
        btnNavSchedule1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        btnNavSchedule1.setFocusPainted(false);
        btnNavSchedule1.setFocusable(false);
        btnNavSchedule1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlNav.add(btnNavSchedule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 40));

        btnNavCases1.setBackground(new java.awt.Color(30, 95, 125));
        btnNavCases1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNavCases1.setForeground(new java.awt.Color(255, 255, 255));
        btnNavCases1.setText("Cases");
        btnNavCases1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        btnNavCases1.setFocusPainted(false);
        btnNavCases1.setFocusable(false);
        btnNavCases1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlNav.add(btnNavCases1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 40));

        btnNavReviews1.setBackground(new java.awt.Color(30, 95, 125));
        btnNavReviews1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNavReviews1.setForeground(new java.awt.Color(255, 255, 255));
        btnNavReviews1.setText("Reviews");
        btnNavReviews1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        btnNavReviews1.setFocusPainted(false);
        btnNavReviews1.setFocusable(false);
        btnNavReviews1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlNav.add(btnNavReviews1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 40));

        btnNavProfile1.setBackground(new java.awt.Color(30, 95, 125));
        btnNavProfile1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNavProfile1.setForeground(new java.awt.Color(255, 255, 255));
        btnNavProfile1.setText("Profile");
        btnNavProfile1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 15, 0, 0));
        btnNavProfile1.setFocusPainted(false);
        btnNavProfile1.setFocusable(false);
        btnNavProfile1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pnlNav.add(btnNavProfile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 160, 40));

        getContentPane().add(pnlNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 180, 550));

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.CardLayout());

        pnlProfile.setBackground(new java.awt.Color(255, 255, 255));
        pnlProfile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfileTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblProfileTitle.setForeground(new java.awt.Color(17, 17, 17));
        lblProfileTitle.setText("Profile");
        pnlProfile.add(lblProfileTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 400, 30));

        lblProfessionalHeader.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblProfessionalHeader.setForeground(new java.awt.Color(38, 117, 154));
        lblProfessionalHeader.setText("Professional Details");
        pnlProfile.add(lblProfessionalHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 55, 275, 22));

        lblContactHeader.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblContactHeader.setForeground(new java.awt.Color(38, 117, 154));
        lblContactHeader.setText("Contact Details");
        pnlProfile.add(lblContactHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 55, 275, 22));

        lblPasswordHeader.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPasswordHeader.setForeground(new java.awt.Color(38, 117, 154));
        lblPasswordHeader.setText("Change Password");
        pnlProfile.add(lblPasswordHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 223, 275, 22));

        lblDoctorID.setText("Doctor ID: ");
        pnlProfile.add(lblDoctorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 85, 275, 18));

        txtDoctorID.setEditable(false);
        txtDoctorID.setText("txtDoctorID");
        pnlProfile.add(txtDoctorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 105, 275, 28));

        lblFirstName.setText("First Name: ");
        pnlProfile.add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 141, 275, 18));

        lblLastName.setText("Last Name: ");
        pnlProfile.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 197, 275, 18));

        lblDepartment.setText("Department: ");
        pnlProfile.add(lblDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 253, 275, 18));

        lblSpecialization.setText("Specialization: ");
        pnlProfile.add(lblSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 309, 100, 16));

        lblOffDay.setText("Off Day: ");
        pnlProfile.add(lblOffDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 365, 60, 16));

        txtFirstName.setEditable(false);
        txtFirstName.setText("txtFirstName");
        pnlProfile.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 161, 275, 28));

        txtLastName.setEditable(false);
        txtLastName.setText("txtLastName");
        pnlProfile.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 217, 275, 28));

        txtDepartment.setEditable(false);
        txtDepartment.setText("txtDepartment");
        pnlProfile.add(txtDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 273, 275, 28));

        txtSpecialization.setEditable(false);
        txtSpecialization.setText("txtSpecialization");
        pnlProfile.add(txtSpecialization, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 329, 275, 28));

        txtOffDay.setEditable(false);
        txtOffDay.setText("txtOffDay");
        pnlProfile.add(txtOffDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 385, 275, 28));

        lblPhone.setText("Phone Number: ");
        pnlProfile.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 85, 275, 18));

        lblEmail.setText("E-mail Address: ");
        pnlProfile.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 141, 275, 18));

        txtPhone.setText("txtPhone");
        pnlProfile.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 105, 275, 28));

        txtEmail.setText("txtEmail");
        pnlProfile.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 161, 275, 28));

        lblCurrentPwd.setText("lblCurrentPwd");
        pnlProfile.add(lblCurrentPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 253, 275, 18));

        pwdCurrent.setText("pwdCurrent");
        pnlProfile.add(pwdCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 273, 275, 28));

        lblNewPwd.setText("lblNewPwd");
        pnlProfile.add(lblNewPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 309, 275, 18));

        pwdNew.setText("pwdNew");
        pnlProfile.add(pwdNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 329, 275, 28));

        lblConfirmPwd.setText("lblConfirmPwd");
        pnlProfile.add(lblConfirmPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 365, 275, 18));

        pwdConfirm.setText("pwdConfirm");
        pnlProfile.add(pwdConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 385, 275, 28));

        lblPwdHint.setText("Leave blank to keep current password");
        pnlProfile.add(lblPwdHint, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 421, 275, 22));

        btnSaveProfile.setBackground(new java.awt.Color(38, 117, 154));
        btnSaveProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSaveProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveProfile.setText("Save");
        pnlProfile.add(btnSaveProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 451, 132, 36));

        btnResetProfile.setBackground(new java.awt.Color(38, 117, 154));
        btnResetProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResetProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnResetProfile.setText("Reset");
        btnResetProfile.setFocusPainted(false);
        pnlProfile.add(btnResetProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 451, 132, 36));

        pnlContent.add(pnlProfile, "profile");

        pnlCases.setBackground(new java.awt.Color(255, 255, 255));
        pnlCases.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCasesTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblCasesTitle.setForeground(new java.awt.Color(17, 17, 17));
        lblCasesTitle.setText("Cases");
        pnlCases.add(lblCasesTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 400, 30));

        tblCases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Case ID", "Patient", "Doctor-in-Charge", "Category", "Type", "Open Date", "Close Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCases.setColumnSelectionAllowed(true);
        tblCases.setSelectionBackground(new java.awt.Color(38, 117, 154));
        tblCases.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblCases.getTableHeader().setReorderingAllowed(false);
        scrCases.setViewportView(tblCases);
        tblCases.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        pnlCases.add(scrCases, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 580, 470));

        pnlContent.add(pnlCases, "cases");

        pnlSchedule.setBackground(new java.awt.Color(255, 255, 255));
        pnlSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblScheduleTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblScheduleTitle.setForeground(new java.awt.Color(17, 17, 17));
        lblScheduleTitle.setText("Schedule");
        pnlSchedule.add(lblScheduleTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 400, 30));

        tblSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSchedule.setSelectionBackground(new java.awt.Color(38, 117, 154));
        tblSchedule.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrSchedule.setViewportView(tblSchedule);

        pnlSchedule.add(scrSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 580, 470));

        pnlContent.add(pnlSchedule, "schedule");

        pnlConsultations.setBackground(new java.awt.Color(255, 255, 255));
        pnlConsultations.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConsultationsTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblConsultationsTitle.setForeground(new java.awt.Color(17, 17, 17));
        lblConsultationsTitle.setText("Consultations");
        pnlConsultations.add(lblConsultationsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 400, 30));

        btnPrevWeek.setBackground(new java.awt.Color(38, 117, 154));
        btnPrevWeek.setForeground(new java.awt.Color(255, 255, 255));
        btnPrevWeek.setText("← Prev Week");
        btnPrevWeek.setFocusPainted(false);
        btnPrevWeek.setRolloverEnabled(false);
        pnlConsultations.add(btnPrevWeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 55, 110, 28));

        btnNextWeek.setBackground(new java.awt.Color(38, 117, 154));
        btnNextWeek.setForeground(new java.awt.Color(255, 255, 255));
        btnNextWeek.setText("Next Week →");
        btnNextWeek.setFocusPainted(false);
        btnNextWeek.setRolloverEnabled(false);
        pnlConsultations.add(btnNextWeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 55, 110, 28));

        lblWeekRange.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblWeekRange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWeekRange.setText("Week of —");
        pnlConsultations.add(lblWeekRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 55, 110, 28));

        tblCalendar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrCalendar.setViewportView(tblCalendar);

        pnlConsultations.add(scrCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 95, 580, 435));

        pnlContent.add(pnlConsultations, "consultations");

        pnlReviews.setBackground(new java.awt.Color(255, 255, 255));
        pnlReviews.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReviewsTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblReviewsTitle.setForeground(new java.awt.Color(17, 17, 17));
        lblReviewsTitle.setText("Reviews");
        pnlReviews.add(lblReviewsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 15, 400, 30));

        tblReviews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblReviews.setSelectionBackground(new java.awt.Color(38, 117, 154));
        tblReviews.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrReviews.setViewportView(tblReviews);

        pnlReviews.add(scrReviews, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 580, 470));

        pnlContent.add(pnlReviews, "reviews");

        getContentPane().add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 620, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DoctorDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNavCases1;
    private javax.swing.JButton btnNavConsultations1;
    private javax.swing.JButton btnNavProfile1;
    private javax.swing.JButton btnNavReviews1;
    private javax.swing.JButton btnNavSchedule1;
    private javax.swing.JButton btnNextWeek;
    private javax.swing.JButton btnPrevWeek;
    private javax.swing.JButton btnResetProfile;
    private javax.swing.JButton btnSaveProfile;
    private javax.swing.JLabel lblCasesTitle;
    private javax.swing.JLabel lblConfirmPwd;
    private javax.swing.JLabel lblConsultationsTitle;
    private javax.swing.JLabel lblContactHeader;
    private javax.swing.JLabel lblCurrentPwd;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblDoctorID;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblNewPwd;
    private javax.swing.JLabel lblOffDay;
    private javax.swing.JLabel lblPasswordHeader;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPortalTitle;
    private javax.swing.JLabel lblProfessionalHeader;
    private javax.swing.JLabel lblProfileTitle;
    private javax.swing.JLabel lblPwdHint;
    private javax.swing.JLabel lblReviewsTitle;
    private javax.swing.JLabel lblScheduleTitle;
    private javax.swing.JLabel lblSpecialization;
    private javax.swing.JLabel lblWeekRange;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlCases;
    private javax.swing.JPanel pnlConsultations;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlNav;
    private javax.swing.JPanel pnlProfile;
    private javax.swing.JPanel pnlReviews;
    private javax.swing.JPanel pnlSchedule;
    private javax.swing.JPasswordField pwdConfirm;
    private javax.swing.JPasswordField pwdCurrent;
    private javax.swing.JPasswordField pwdNew;
    private javax.swing.JScrollPane scrCalendar;
    private javax.swing.JScrollPane scrCases;
    private javax.swing.JScrollPane scrReviews;
    private javax.swing.JScrollPane scrSchedule;
    private javax.swing.JTable tblCalendar;
    private javax.swing.JTable tblCases;
    private javax.swing.JTable tblReviews;
    private javax.swing.JTable tblSchedule;
    private javax.swing.JTextField txtDepartment;
    private javax.swing.JTextField txtDoctorID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtOffDay;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSpecialization;
    // End of variables declaration//GEN-END:variables
}
