/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Doctor;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sascha
 */
public class PrescriptionDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PrescriptionDialog.class.getName());

    private DoctorServices doctor;
    // items already added to the prescription being built: {drugId, drugName, dosage, frequency, duration, instructions}
    private ArrayList<String[]> pendingItems = new ArrayList<>();
    private int selectedDrugId = -1;
    private String selectedDrugName = "";
    private String selectedForm = "";

    // Nothing is written to file from this dialog. The caller (ConsultationsDialog) only
    // applies these items when its own "Save Progress"/"Complete Consultation" is clicked.
    private boolean saved = false;
    private ArrayList<String[]> resultItems = new ArrayList<>();

    /**
     * Creates new form PrescriptionDialog
     */
    public PrescriptionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    // Used by the Consultation dialog to draft a prescription for one consultation.
    // initialItems is the current draft (already-saved items, plus anything added earlier
    // this session) so re-opening this dialog continues from where the doctor left off.
    public PrescriptionDialog(java.awt.Frame parent, boolean modal, DoctorServices doctor, int consultId, ArrayList<String[]> initialItems) {
        super(parent, modal);
        initComponents();
        this.doctor = doctor;

        lblPrescriptionMeta.setText("Consultation #" + consultId);
        txtDrugSearch.setText("");
        txtDosage.setText("");
        txtFrequency.setText("");
        txtInstructions.setText("");

        ArrayList<String> forms = doctor.getDrugForms();
        cmbFormFilter.setModel(new javax.swing.DefaultComboBoxModel<>(forms.toArray(new String[0])));

        pendingItems = new ArrayList<>(initialItems);
        refreshItemsTable();
        lblPrescriptionHeader.setText(pendingItems.isEmpty() ? "Write Prescription" : "Edit Prescription");

        if (!doctor.canEditConsultation()) {
            lblSelectedDrug.setText("This consultation can no longer be edited.");
            setInputsEnabled(false);
        } else {
            searchDrugs();
        }
    }

    // true once the doctor clicked "Save Prescription" in this dialog
    public boolean isSaved() {
        return saved;
    }

    // the drafted items, only meaningful when isSaved() is true
    public ArrayList<String[]> getResultItems() {
        return resultItems;
    }

    private void setInputsEnabled(boolean enabled) {
        cmbFormFilter.setEnabled(enabled);
        txtDrugSearch.setEnabled(enabled);
        tblDrugResults.setEnabled(enabled);
        txtDosage.setEnabled(enabled);
        txtFrequency.setEnabled(enabled);
        spnDuration.setEnabled(enabled);
        txtInstructions.setEnabled(enabled);
        btnAddItem.setEnabled(enabled);
        btnRemoveItem.setEnabled(enabled);
        btnSavePrescription.setEnabled(enabled);
    }

    private void searchDrugs() {
        String form = "All";
        if (cmbFormFilter.getSelectedItem() != null) {
            form = cmbFormFilter.getSelectedItem().toString();
        }
        DefaultTableModel model = (DefaultTableModel) tblDrugResults.getModel();
        model.setRowCount(0);
        for (Object[] row : doctor.searchDrugs(form, txtDrugSearch.getText())) {
            model.addRow(row);
        }
    }

    private void refreshItemsTable() {
        DefaultTableModel model = (DefaultTableModel) tblPrescriptionItems.getModel();
        model.setRowCount(0);
        for (String[] item : pendingItems) {
            model.addRow(new Object[]{item[1], item[2], item[3], item[4]});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrescriptionHeader = new javax.swing.JLabel();
        lblPrescriptionMeta = new javax.swing.JLabel();
        lblPrescriptionFilterHeader = new javax.swing.JLabel();
        cmbFormFilter = new javax.swing.JComboBox<>();
        txtDrugSearch = new javax.swing.JTextField();
        scrDrugResults = new javax.swing.JScrollPane();
        tblDrugResults = new javax.swing.JTable();
        lblSelectedDrug = new javax.swing.JLabel();
        lblDosageHeader = new javax.swing.JLabel();
        lblDosageUnit = new javax.swing.JLabel();
        txtDosage = new javax.swing.JTextField();
        lblFrequency = new javax.swing.JLabel();
        txtFrequency = new javax.swing.JTextField();
        lblDuration = new javax.swing.JLabel();
        spnDuration = new javax.swing.JSpinner();
        lblInstructions = new javax.swing.JLabel();
        txtInstructions = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        lblItemsHeader = new javax.swing.JLabel();
        scrPrescriptionItems = new javax.swing.JScrollPane();
        tblPrescriptionItems = new javax.swing.JTable();
        btnRemoveItem = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSavePrescription = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Write Prescription");
        setModal(true);
        setName("prescriptions"); // NOI18N
        setPreferredSize(new java.awt.Dimension(570, 795));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrescriptionHeader.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPrescriptionHeader.setText("lblPrescriptionHeader");
        getContentPane().add(lblPrescriptionHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 26));

        lblPrescriptionMeta.setForeground(new java.awt.Color(102, 102, 102));
        lblPrescriptionMeta.setText("lblPrescriptionMeta");
        getContentPane().add(lblPrescriptionMeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 48, 400, 18));

        lblPrescriptionFilterHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrescriptionFilterHeader.setText("Select Drug: ");
        getContentPane().add(lblPrescriptionFilterHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, 300, 18));

        cmbFormFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFormFilter.addActionListener(this::cmbFormFilter);
        getContentPane().add(cmbFormFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 98, 170, 26));

        txtDrugSearch.setText("Search drug name...");
        txtDrugSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDrugSearch(evt);
            }
        });
        getContentPane().add(txtDrugSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 98, 320, 26));

        tblDrugResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug Name", "Form", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDrugResults.setColumnSelectionAllowed(true);
        tblDrugResults.setRowHeight(25);
        tblDrugResults.setSelectionBackground(new java.awt.Color(38, 117, 154));
        tblDrugResults.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblDrugResults.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblDrugResults.getTableHeader().setReorderingAllowed(false);
        tblDrugResults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDrugResults(evt);
            }
        });
        scrDrugResults.setViewportView(tblDrugResults);
        tblDrugResults.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(scrDrugResults, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 134, 520, 140));

        lblSelectedDrug.setForeground(new java.awt.Color(102, 102, 102));
        lblSelectedDrug.setText("Selected: —");
        getContentPane().add(lblSelectedDrug, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 284, 520, 18));

        lblDosageHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDosageHeader.setText("Dosage Details:");
        getContentPane().add(lblDosageHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 312, 300, 18));

        lblDosageUnit.setText("Dosage");
        getContentPane().add(lblDosageUnit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 334, 150, 16));

        txtDosage.setText("txtDosage");
        getContentPane().add(txtDosage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 352, 150, 26));

        lblFrequency.setText("Frequency");
        getContentPane().add(lblFrequency, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 334, 150, 16));

        txtFrequency.setText("txtFrequency");
        getContentPane().add(txtFrequency, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 352, 150, 26));

        lblDuration.setText("Duration (days)");
        getContentPane().add(lblDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 334, 160, 16));

        spnDuration.setModel(new javax.swing.SpinnerNumberModel(1, 1, 90, 1));
        getContentPane().add(spnDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 352, 160, 26));

        lblInstructions.setText("Instructions (e.g. take after meal):");
        getContentPane().add(lblInstructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 388, 400, 16));

        txtInstructions.setText("txtInstructions");
        getContentPane().add(txtInstructions, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 406, 520, 26));

        btnAddItem.setBackground(new java.awt.Color(38, 117, 154));
        btnAddItem.setForeground(new java.awt.Color(255, 255, 255));
        btnAddItem.setText("+ Add Drug to Prescription");
        btnAddItem.setFocusPainted(false);
        btnAddItem.addActionListener(this::btnAddItem);
        getContentPane().add(btnAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 442, 520, 30));

        lblItemsHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblItemsHeader.setText("Prescription Items:");
        getContentPane().add(lblItemsHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 482, 300, 18));

        tblPrescriptionItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drug", "Dosage", "Frequency", "Days"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrescriptionItems.setColumnSelectionAllowed(true);
        tblPrescriptionItems.setRowHeight(25);
        tblPrescriptionItems.setSelectionBackground(new java.awt.Color(38, 117, 154));
        tblPrescriptionItems.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblPrescriptionItems.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblPrescriptionItems.getTableHeader().setReorderingAllowed(false);
        scrPrescriptionItems.setViewportView(tblPrescriptionItems);
        tblPrescriptionItems.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(scrPrescriptionItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 502, 520, 130));

        btnRemoveItem.setText("Remove Selected");
        btnRemoveItem.setFocusPainted(false);
        btnRemoveItem.addActionListener(this::btnRemoveItem);
        getContentPane().add(btnRemoveItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 646, 250, 32));

        btnCancel.setBackground(new java.awt.Color(38, 117, 154));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancel);
        getContentPane().add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 700, 250, 36));

        btnSavePrescription.setBackground(new java.awt.Color(38, 117, 154));
        btnSavePrescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSavePrescription.setForeground(new java.awt.Color(255, 255, 255));
        btnSavePrescription.setText("Save Prescription");
        btnSavePrescription.addActionListener(this::btnSavePrescription);
        getContentPane().add(btnSavePrescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 250, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFormFilter(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFormFilter
        searchDrugs();
    }//GEN-LAST:event_cmbFormFilter

    private void btnAddItem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItem
        if (selectedDrugId < 0) {
            JOptionPane.showMessageDialog(this, "Please select a drug from the results above.");
            return;
        }
        String dosage = txtDosage.getText();
        String frequency = txtFrequency.getText();
        String instructions = txtInstructions.getText();
        String unit = doctor.getDosageUnit(selectedForm);

        String error = doctor.checkPrescriptionItem(unit, dosage, frequency, instructions);
        if (error != null) {
            JOptionPane.showMessageDialog(this, error);
            return;
        }

        String duration = String.valueOf(spnDuration.getValue());
        pendingItems.add(new String[]{String.valueOf(selectedDrugId), selectedDrugName,
            dosage.trim(), frequency.trim(), duration, instructions.trim()});
        refreshItemsTable();

        txtDosage.setText("");
        txtFrequency.setText("");
        txtInstructions.setText("");
        spnDuration.setValue(1);
    }//GEN-LAST:event_btnAddItem

    private void btnRemoveItem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItem
        int row = tblPrescriptionItems.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select an item to remove.");
            return;
        }
        pendingItems.remove(row);
        refreshItemsTable();
    }//GEN-LAST:event_btnRemoveItem

    private void btnSavePrescription(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePrescription
        if (pendingItems.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please add at least one drug to the prescription.");
            return;
        }
        resultItems = pendingItems;
        saved = true;
        dispose();
    }//GEN-LAST:event_btnSavePrescription

    private void btnCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel
        dispose();
    }//GEN-LAST:event_btnCancel

    private void tblDrugResults(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDrugResults
        int row = tblDrugResults.getSelectedRow();
        if (row < 0) {
            return;
        }
        selectedDrugId = doctor.getDrugResultId(row);
        selectedDrugName = tblDrugResults.getValueAt(row, 0).toString();
        selectedForm = tblDrugResults.getValueAt(row, 1).toString();
        lblSelectedDrug.setText("Selected: " + selectedDrugName);
        lblDosageUnit.setText(doctor.getDosageUnit(selectedForm));
    }//GEN-LAST:event_tblDrugResults

    private void txtDrugSearch(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDrugSearch
        searchDrugs();
    }//GEN-LAST:event_txtDrugSearch


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                PrescriptionDialog dialog = new PrescriptionDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JButton btnSavePrescription;
    private javax.swing.JComboBox<String> cmbFormFilter;
    private javax.swing.JLabel lblDosageHeader;
    private javax.swing.JLabel lblDosageUnit;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblFrequency;
    private javax.swing.JLabel lblInstructions;
    private javax.swing.JLabel lblItemsHeader;
    private javax.swing.JLabel lblPrescriptionFilterHeader;
    private javax.swing.JLabel lblPrescriptionHeader;
    private javax.swing.JLabel lblPrescriptionMeta;
    private javax.swing.JLabel lblSelectedDrug;
    private javax.swing.JScrollPane scrDrugResults;
    private javax.swing.JScrollPane scrPrescriptionItems;
    private javax.swing.JSpinner spnDuration;
    private javax.swing.JTable tblDrugResults;
    private javax.swing.JTable tblPrescriptionItems;
    private javax.swing.JTextField txtDosage;
    private javax.swing.JTextField txtDrugSearch;
    private javax.swing.JTextField txtFrequency;
    private javax.swing.JTextField txtInstructions;
    // End of variables declaration//GEN-END:variables
}
