package Patient;

import HelperFunction.FileHandling;
import java.util.ArrayList;
import java.util.TreeMap;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class PatientLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PatientLogin.class.getName());

    /**
     * Creates new form PatientLogin
     */
    public PatientLogin() {
        initComponents();
        setLocationRelativeTo(null);
        getRootPane().setDefaultButton(btnLogin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblHospitalName = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblUserID1 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        pwdPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HMS Patient Portal v1.0 ");
        setResizable(false);
        getContentPane().setLayout(null);

        pnlLeft.setBackground(new java.awt.Color(38, 117, 154));
        pnlLeft.setToolTipText("");
        pnlLeft.setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        lblLogo.setToolTipText("");
        pnlLeft.add(lblLogo);
        lblLogo.setBounds(140, 170, 106, 94);

        lblHospitalName.setBackground(new java.awt.Color(255, 255, 255));
        lblHospitalName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHospitalName.setText("APU Medical Centre");
        pnlLeft.add(lblHospitalName);
        lblHospitalName.setBounds(90, 270, 240, 24);
        lblHospitalName.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(pnlLeft);
        pnlLeft.setBounds(0, 0, 393, 600);

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitle.setText("PATIENT PORTAL LOGIN");
        pnlRight.add(lblTitle);
        lblTitle.setBounds(40, 130, 330, 80);

        lblPassword.setText("Password");
        lblPassword.setToolTipText("");
        pnlRight.add(lblPassword);
        lblPassword.setBounds(40, 290, 120, 16);

        lblUserID1.setText("E-Mail");
        pnlRight.add(lblUserID1);
        lblUserID1.setBounds(40, 220, 120, 16);

        txtUserID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlRight.add(txtUserID);
        txtUserID.setBounds(40, 240, 320, 30);

        btnLogin.setBackground(new java.awt.Color(38, 117, 154));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("LOGIN");
        btnLogin.setFocusPainted(false);
        btnLogin.setRolloverEnabled(false);
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        pnlRight.add(btnLogin);
        btnLogin.setBounds(80, 410, 240, 32);
        pnlRight.add(pwdPassword);
        pwdPassword.setBounds(40, 310, 320, 30);

        getContentPane().add(pnlRight);
        pnlRight.setBounds(393, 0, 407, 600);

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String input = txtUserID.getText().trim();
        String password = new String(pwdPassword.getPassword());
        
        if (input.isEmpty() || password.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your email and password.");
            return;
        }
        
        TreeMap<Integer, ArrayList<String>> users = FileHandling.readAllRecords("Users.txt");
        //u: 0 is first, 1 is last, 2 dob, 3 gender, 4 phone, 5 email, 6 password, 7 role, 8 deleted
        if (users !=null){
            for (Integer id : users.keySet()){
                ArrayList<String> u = users.get(id);
                boolean emailMatch = u.get(5).equalsIgnoreCase(input);
                
                if(emailMatch && u.get(6).equals(password)
                    && u.get(7).equals("Patient") && u.get(8).equals("0")){
                    new PatientDashboard(id).setVisible(true);
                    dispose();
                    return;
                }
                
            }
        }
        
        JOptionPane.showMessageDialog(this, "Invalid email or password.");
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       

       javax.swing.UIManager.put("Button.focus", new java.awt.Color(0, 0, 0, 0));
       javax.swing.UIManager.put("RadioButton.focus", new java.awt.Color(0, 0, 0, 0));

       /* Create and display the form */
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PatientLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserID1;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtUserID;
    // End of variables declaration//GEN-END:variables
}
