package Patient;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class PatientLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PatientLogin.class.getName());

    /**
     * Creates new form PatientLogin
     */
    public PatientLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblHospitalName = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblUserID1 = new javax.swing.JLabel();
        txtUserID1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HMS Patient Portal v1.0 ");
        setResizable(false);
        getContentPane().setLayout(null);

        pnlLeft.setBackground(new java.awt.Color(38, 117, 154));
        pnlLeft.setToolTipText("");
        pnlLeft.setLayout(null);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        lblLogo.setToolTipText("");
        pnlLeft.add(lblLogo);
        lblLogo.setBounds(140, 170, 106, 94);

        lblHospitalName.setBackground(new java.awt.Color(255, 255, 255));
        lblHospitalName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblHospitalName.setText("APU Medical Centre");
        pnlLeft.add(lblHospitalName);
        lblHospitalName.setBounds(90, 270, 240, 24);
        lblHospitalName.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(pnlLeft);
        pnlLeft.setBounds(0, 0, 393, 600);

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblTitle.setText("PATIENT PORTAL LOGIN");
        pnlRight.add(lblTitle);
        lblTitle.setBounds(40, 130, 330, 80);

        lblPassword.setText("Password");
        lblPassword.setToolTipText("");
        pnlRight.add(lblPassword);
        lblPassword.setBounds(40, 290, 120, 16);

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlRight.add(txtPassword);
        txtPassword.setBounds(40, 310, 320, 30);

        lblUserID1.setText("E-Mail");
        pnlRight.add(lblUserID1);
        lblUserID1.setBounds(40, 220, 120, 16);

        txtUserID1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlRight.add(txtUserID1);
        txtUserID1.setBounds(40, 240, 320, 30);

        jButton1.setBackground(new java.awt.Color(38, 117, 154));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        pnlRight.add(jButton1);
        jButton1.setBounds(80, 410, 240, 32);

        getContentPane().add(pnlRight);
        pnlRight.setBounds(393, 0, 407, 600);

        setBounds(0, 0, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PatientLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserID1;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserID1;
    // End of variables declaration//GEN-END:variables
}
