/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Admin;

import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sascha
 */
public class AddAssetDialog extends javax.swing.JDialog {

    private final AdminServices admin;
    private final String category;
    private boolean saved = false;

    public AddAssetDialog(Frame parent, AdminServices admin, String category) {
        super(parent, true);
        this.admin = admin;
        this.category = category;
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Add New Asset");

        lblCategory.setText("Category: " + category);

        java.util.ArrayList<String> types = admin.getAssetTypes(category);
        boolean hasTypes = !types.isEmpty();
        lblType.setVisible(hasTypes);
        cmbType.setVisible(hasTypes);
        if (hasTypes) {
            cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(types.toArray(new String[0])));
        }
    }

    public boolean isSaved() {
        return saved;
    }

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {
        String type = cmbType.isVisible() ? (String) cmbType.getSelectedItem() : null;
        String result = admin.addAsset(category, type);
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        saved = true;
        dispose();
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCategory = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Asset");
        setResizable(false);
        getContentPane().setLayout(null);

        lblCategory.setFont(new java.awt.Font("Segoe UI", 1, 13));
        lblCategory.setText("Category:");
        getContentPane().add(lblCategory);
        lblCategory.setBounds(20, 20, 320, 24);

        lblType.setText("Type:");
        getContentPane().add(lblType);
        lblType.setBounds(20, 60, 100, 20);

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        getContentPane().add(cmbType);
        cmbType.setBounds(20, 84, 320, 26);

        btnAdd.setBackground(new java.awt.Color(38, 117, 154));
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);
        getContentPane().add(btnAdd);
        btnAdd.setBounds(90, 130, 100, 36);

        btnCancel.setBackground(new java.awt.Color(150, 150, 150));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel);
        btnCancel.setBounds(210, 130, 100, 36);

        setBounds(0, 0, 380, 210);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblType;
    // End of variables declaration//GEN-END:variables
}
