/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JButton;

/**
 *
 * @author User
 */
public class AdminDashboard extends javax.swing.JFrame {

    private final Color NAV_BG = new Color(30, 95, 125);
    private final Color BLUE = new Color(38, 117, 154);

    private void showPage(String cardName, JButton activeButton) {
        CardLayout cardLayout = (CardLayout) pnlContent.getLayout();
        cardLayout.show(pnlContent, cardName);

        JButton[] menu = {btnNavUsers, btnNavAssign, btnNavAssets, btnNavBilling};
        for (JButton b : menu) {
            b.setBackground(NAV_BG);
            b.setForeground(Color.WHITE);
        }
        activeButton.setBackground(Color.WHITE);
        activeButton.setForeground(BLUE);
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblPortalTitle = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        pnlNav = new javax.swing.JPanel();
        btnNavUsers = new javax.swing.JButton();
        btnNavAssign = new javax.swing.JButton();
        btnNavAssets = new javax.swing.JButton();
        btnNavBilling = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();
        pnlUsers = new javax.swing.JPanel();
        lblUsersTitle = new javax.swing.JLabel();
        pnlAssign = new javax.swing.JPanel();
        lblAssignTitle = new javax.swing.JLabel();
        pnlAssets = new javax.swing.JPanel();
        lblAssetsTitle = new javax.swing.JLabel();
        pnlBilling = new javax.swing.JPanel();
        lblBillingTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HMS Ademin Portal");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        pnlHeader.setBackground(new java.awt.Color(38, 117, 154));
        pnlHeader.setLayout(null);

        lblPortalTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblPortalTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPortalTitle.setText("APU Medical Centre - Admin Portal");
        pnlHeader.add(lblPortalTitle);
        lblPortalTitle.setBounds(20, 10, 450, 30);

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblWelcome.setText("Welcome Admin");
        pnlHeader.add(lblWelcome);
        lblWelcome.setBounds(470, 10, 300, 30);

        getContentPane().add(pnlHeader);
        pnlHeader.setBounds(0, 0, 800, 50);

        pnlNav.setBackground(new java.awt.Color(30, 95, 125));
        pnlNav.setLayout(null);

        btnNavUsers.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNavUsers.setForeground(new java.awt.Color(38, 117, 154));
        btnNavUsers.setText("Manage Users");
        btnNavUsers.setContentAreaFilled(false);
        btnNavUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavUsers.setFocusPainted(false);
        btnNavUsers.setRolloverEnabled(false);
        btnNavUsers.addActionListener(this::btnNavUsersActionPerformed);
        pnlNav.add(btnNavUsers);
        btnNavUsers.setBounds(10, 20, 160, 40);

        btnNavAssign.setBackground(new java.awt.Color(30, 95, 125));
        btnNavAssign.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNavAssign.setForeground(new java.awt.Color(255, 255, 255));
        btnNavAssign.setText("Doctor Assignment");
        btnNavAssign.setContentAreaFilled(false);
        btnNavAssign.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavAssign.setFocusPainted(false);
        btnNavAssign.setRolloverEnabled(false);
        btnNavAssign.addActionListener(this::btnNavAssignActionPerformed);
        pnlNav.add(btnNavAssign);
        btnNavAssign.setBounds(10, 70, 160, 40);

        btnNavAssets.setBackground(new java.awt.Color(30, 95, 125));
        btnNavAssets.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNavAssets.setForeground(new java.awt.Color(255, 255, 255));
        btnNavAssets.setText("Hospital Assets");
        btnNavAssets.setContentAreaFilled(false);
        btnNavAssets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavAssets.setFocusPainted(false);
        btnNavAssets.setRolloverEnabled(false);
        btnNavAssets.addActionListener(this::btnNavAssetsActionPerformed);
        pnlNav.add(btnNavAssets);
        btnNavAssets.setBounds(10, 120, 160, 40);

        btnNavBilling.setBackground(new java.awt.Color(30, 95, 125));
        btnNavBilling.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNavBilling.setForeground(new java.awt.Color(255, 255, 255));
        btnNavBilling.setText("Rates & Insurance");
        btnNavBilling.setContentAreaFilled(false);
        btnNavBilling.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNavBilling.setFocusPainted(false);
        btnNavBilling.setRolloverEnabled(false);
        btnNavBilling.addActionListener(this::btnNavBillingActionPerformed);
        pnlNav.add(btnNavBilling);
        btnNavBilling.setBounds(10, 170, 160, 40);

        btnLogout.setBackground(new java.awt.Color(30, 95, 125));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LOGOUT");
        btnLogout.setContentAreaFilled(false);
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusPainted(false);
        btnLogout.setRolloverEnabled(false);
        pnlNav.add(btnLogout);
        btnLogout.setBounds(10, 450, 160, 40);

        getContentPane().add(pnlNav);
        pnlNav.setBounds(0, 50, 180, 550);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.CardLayout());

        pnlUsers.setBackground(new java.awt.Color(255, 255, 255));
        pnlUsers.setLayout(null);

        lblUsersTitle.setText("Manage End Users");
        pnlUsers.add(lblUsersTitle);
        lblUsersTitle.setBounds(0, 0, 98, 16);

        pnlContent.add(pnlUsers, "users");

        pnlAssign.setBackground(new java.awt.Color(255, 255, 255));
        pnlAssign.setLayout(null);

        lblAssignTitle.setText("Doctor Assignment");
        pnlAssign.add(lblAssignTitle);
        lblAssignTitle.setBounds(0, 0, 103, 16);

        pnlContent.add(pnlAssign, "assign");

        pnlAssets.setBackground(new java.awt.Color(255, 255, 255));
        pnlAssets.setLayout(null);

        lblAssetsTitle.setText("Hospital Assets");
        pnlAssets.add(lblAssetsTitle);
        lblAssetsTitle.setBounds(0, 0, 81, 16);

        pnlContent.add(pnlAssets, "assets");

        pnlBilling.setBackground(new java.awt.Color(255, 255, 255));
        pnlBilling.setLayout(null);

        lblBillingTitle.setText("Rates & Insurance");
        pnlBilling.add(lblBillingTitle);
        lblBillingTitle.setBounds(0, 0, 95, 16);

        pnlContent.add(pnlBilling, "billing");

        getContentPane().add(pnlContent);
        pnlContent.setBounds(180, 50, 620, 550);

        setBounds(0, 0, 814, 608);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNavUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavUsersActionPerformed
        // TODO add your handling code here:
        showPage("users", btnNavUsers);
    }//GEN-LAST:event_btnNavUsersActionPerformed

    private void btnNavAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavAssignActionPerformed
        // TODO add your handling code here:
        showPage("assign", btnNavAssign);
    }//GEN-LAST:event_btnNavAssignActionPerformed

    private void btnNavAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavAssetsActionPerformed
        // TODO add your handling code here:
        showPage("assets", btnNavAssets);
    }//GEN-LAST:event_btnNavAssetsActionPerformed

    private void btnNavBillingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavBillingActionPerformed
        // TODO add your handling code here:
        showPage("billing", btnNavBilling);
    }//GEN-LAST:event_btnNavBillingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNavAssets;
    private javax.swing.JButton btnNavAssign;
    private javax.swing.JButton btnNavBilling;
    private javax.swing.JButton btnNavUsers;
    private javax.swing.JLabel lblAssetsTitle;
    private javax.swing.JLabel lblAssignTitle;
    private javax.swing.JLabel lblBillingTitle;
    private javax.swing.JLabel lblPortalTitle;
    private javax.swing.JLabel lblUsersTitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlAssets;
    private javax.swing.JPanel pnlAssign;
    private javax.swing.JPanel pnlBilling;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlNav;
    private javax.swing.JPanel pnlUsers;
    // End of variables declaration//GEN-END:variables
}
