/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Admin;

import java.awt.Frame;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sascha
 */
public class AdmissionDialog extends javax.swing.JDialog {

    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("dd-MM-yyyy");

    private final AdminServices admin;
    private final ArrayList<Integer> caseIds = new ArrayList<>();
    private final ArrayList<Integer> bedIds = new ArrayList<>();
    private boolean saved = false;

    public AdmissionDialog(Frame parent, AdminServices admin) {
        super(parent, true);
        this.admin = admin;
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("New Admission");

        caseIds.clear();
        ArrayList<String> caseLabels = new ArrayList<>();
        for (Object[] row : admin.getCasesForAdmission()) {
            caseIds.add((Integer) row[0]);
            caseLabels.add((String) row[1]);
        }
        cmbCase.setModel(new javax.swing.DefaultComboBoxModel<>(caseLabels.toArray(new String[0])));
        refreshBeds();
        txtDate.setText(LocalDate.now().format(DATE_FORMAT));
    }

    private void refreshBeds() {
        bedIds.clear();
        int caseIndex = cmbCase.getSelectedIndex();
        if (caseIndex < 0) {
            cmbBed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));
            return;
        }
        ArrayList<String> bedLabels = new ArrayList<>();
        for (Object[] row : admin.getAvailableBeds(caseIds.get(caseIndex))) {
            bedIds.add((Integer) row[0]);
            bedLabels.add((String) row[1]);
        }
        cmbBed.setModel(new javax.swing.DefaultComboBoxModel<>(bedLabels.toArray(new String[0])));
    }

    public boolean isSaved() {
        return saved;
    }

    private void cmbCaseActionPerformed(java.awt.event.ActionEvent evt) {
        refreshBeds();
    }

    private void btnAdmitActionPerformed(java.awt.event.ActionEvent evt) {
        int caseIndex = cmbCase.getSelectedIndex();
        int bedIndex = cmbBed.getSelectedIndex();
        if (caseIndex < 0 || bedIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a case and an available bed.");
            return;
        }
        String result = admin.createAdmission(caseIds.get(caseIndex), bedIds.get(bedIndex),
                txtDate.getText(), txtRemarks.getText());
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        saved = true;
        dispose();
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCase = new javax.swing.JLabel();
        cmbCase = new javax.swing.JComboBox<>();
        lblBed = new javax.swing.JLabel();
        cmbBed = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblRemarks = new javax.swing.JLabel();
        txtRemarks = new javax.swing.JTextField();
        btnAdmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Admission");
        setResizable(false);
        getContentPane().setLayout(null);

        lblCase.setText("Case:");
        getContentPane().add(lblCase);
        lblCase.setBounds(20, 20, 140, 20);

        cmbCase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cmbCase.addActionListener(this::cmbCaseActionPerformed);
        getContentPane().add(cmbCase);
        cmbCase.setBounds(20, 44, 400, 26);

        lblBed.setText("Available Bed:");
        getContentPane().add(lblBed);
        lblBed.setBounds(20, 84, 140, 20);

        cmbBed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        getContentPane().add(cmbBed);
        cmbBed.setBounds(20, 108, 400, 26);

        lblDate.setText("Admission Date (dd-MM-yyyy):");
        getContentPane().add(lblDate);
        lblDate.setBounds(20, 148, 220, 20);

        getContentPane().add(txtDate);
        txtDate.setBounds(20, 172, 180, 26);

        lblRemarks.setText("Remarks:");
        getContentPane().add(lblRemarks);
        lblRemarks.setBounds(20, 212, 140, 20);

        getContentPane().add(txtRemarks);
        txtRemarks.setBounds(20, 236, 400, 26);

        btnAdmit.setBackground(new java.awt.Color(38, 117, 154));
        btnAdmit.setForeground(new java.awt.Color(255, 255, 255));
        btnAdmit.setText("Admit");
        btnAdmit.addActionListener(this::btnAdmitActionPerformed);
        getContentPane().add(btnAdmit);
        btnAdmit.setBounds(140, 285, 100, 36);

        btnCancel.setBackground(new java.awt.Color(150, 150, 150));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel);
        btnCancel.setBounds(260, 285, 100, 36);

        setBounds(0, 0, 440, 365);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmit;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cmbBed;
    private javax.swing.JComboBox<String> cmbCase;
    private javax.swing.JLabel lblBed;
    private javax.swing.JLabel lblCase;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblRemarks;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtRemarks;
    // End of variables declaration//GEN-END:variables
}
