/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Admin;

import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sascha
 */
public class BedsDialog extends javax.swing.JDialog {

    private final AdminServices admin;
    private final int wardId;

    public BedsDialog(Frame parent, AdminServices admin, int wardId, String wardLabel) {
        super(parent, true);
        this.admin = admin;
        this.wardId = wardId;
        initComponents();
        setLocationRelativeTo(parent);

        lblHeader.setText("Beds in " + wardLabel);
        loadBeds();
    }

    private void loadBeds() {
        DefaultTableModel model = (DefaultTableModel) tblBeds.getModel();
        model.setRowCount(0);
        for (Object[] row : admin.getBeds(wardId)) {
            model.addRow(new Object[]{row[0]});
        }
    }

    private void btnAddBedActionPerformed(java.awt.event.ActionEvent evt) {
        String result = admin.addBed(wardId);
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        loadBeds();
    }

    private void btnRemoveBedActionPerformed(java.awt.event.ActionEvent evt) {
        int row = tblBeds.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a bed from the list.");
            return;
        }
        int bedId = (Integer) tblBeds.getValueAt(row, 0);
        String result = admin.removeBed(bedId);
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        loadBeds();
    }

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        scrBeds = new javax.swing.JScrollPane();
        tblBeds = new javax.swing.JTable();
        btnAddBed = new javax.swing.JButton();
        btnRemoveBed = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Beds");
        setResizable(false);
        getContentPane().setLayout(null);

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lblHeader.setText("Beds");
        getContentPane().add(lblHeader);
        lblHeader.setBounds(20, 15, 320, 24);

        tblBeds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Bed ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBeds.getTableHeader().setReorderingAllowed(false);
        tblBeds.setSelectionBackground(new java.awt.Color(38, 117, 154));
        tblBeds.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrBeds.setViewportView(tblBeds);
        getContentPane().add(scrBeds);
        scrBeds.setBounds(20, 50, 320, 280);

        btnAddBed.setBackground(new java.awt.Color(38, 117, 154));
        btnAddBed.setForeground(new java.awt.Color(255, 255, 255));
        btnAddBed.setText("Add Bed");
        btnAddBed.addActionListener(this::btnAddBedActionPerformed);
        getContentPane().add(btnAddBed);
        btnAddBed.setBounds(20, 345, 140, 32);

        btnRemoveBed.setBackground(new java.awt.Color(38, 117, 154));
        btnRemoveBed.setForeground(new java.awt.Color(255, 255, 255));
        btnRemoveBed.setText("Remove Selected");
        btnRemoveBed.addActionListener(this::btnRemoveBedActionPerformed);
        getContentPane().add(btnRemoveBed);
        btnRemoveBed.setBounds(170, 345, 170, 32);

        btnClose.setBackground(new java.awt.Color(150, 150, 150));
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(this::btnCloseActionPerformed);
        getContentPane().add(btnClose);
        btnClose.setBounds(120, 390, 120, 32);

        setBounds(0, 0, 380, 460);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBed;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRemoveBed;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JScrollPane scrBeds;
    private javax.swing.JTable tblBeds;
    // End of variables declaration//GEN-END:variables
}
