/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Admin;

import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 * Add/edit dialog shared by the Drug Catalogue and Diagnostic Service
 * Catalogue pages. kind selects which set of fields is shown:
 * "drug" -> name, form, price. "service" -> name, category, type, price.
 *
 * @author Sascha
 */
public class CatalogueItemDialog extends javax.swing.JDialog {

    private final AdminServices admin;
    private final String kind;
    private final Integer editingId;

    public CatalogueItemDialog(Frame parent, AdminServices admin, String kind, Object[] existingRow) {
        super(parent, true);
        this.admin = admin;
        this.kind = kind;
        initComponents();
        setLocationRelativeTo(parent);

        boolean isDrug = kind.equals("drug");
        lblField1.setText(isDrug ? "Form:" : "Category:");
        lblField2.setVisible(!isDrug);
        cmbField2.setVisible(!isDrug);

        if (isDrug) {
            cmbField1.setModel(new javax.swing.DefaultComboBoxModel<>(admin.getDrugForms().toArray(new String[0])));
        } else {
            cmbField1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"laboratory", "imaging"}));
            lblField2.setText("Type:");
            refreshServiceTypes();
        }

        if (existingRow == null) {
            editingId = null;
            setTitle(isDrug ? "Add Drug" : "Add Diagnostic Service");
        } else {
            editingId = (Integer) existingRow[0];
            setTitle(isDrug ? "Edit Drug" : "Edit Diagnostic Service");
            txtName.setText((String) existingRow[1]);
            if (isDrug) {
                cmbField1.setSelectedItem(existingRow[2]);
                txtPrice.setText(String.valueOf(existingRow[3]));
            } else {
                cmbField1.setSelectedItem(existingRow[2]);
                refreshServiceTypes();
                cmbField2.setSelectedItem(existingRow[3]);
                txtPrice.setText(String.valueOf(existingRow[4]));
            }
        }
    }

    private void refreshServiceTypes() {
        String category = (String) cmbField1.getSelectedItem();
        cmbField2.setModel(new javax.swing.DefaultComboBoxModel<>(admin.getServiceTypes(category).toArray(new String[0])));
    }

    private boolean saved = false;

    public boolean isSaved() {
        return saved;
    }

    private void cmbField1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (!kind.equals("drug")) {
            refreshServiceTypes();
        }
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        String name = txtName.getText();
        String price = txtPrice.getText();
        String result;
        if (kind.equals("drug")) {
            String form = (String) cmbField1.getSelectedItem();
            result = editingId == null ? admin.addDrug(name, form, price) : admin.updateDrug(editingId, name, form, price);
        } else {
            String category = (String) cmbField1.getSelectedItem();
            String type = (String) cmbField2.getSelectedItem();
            result = editingId == null
                    ? admin.addService(name, category, type, price)
                    : admin.updateService(editingId, name, category, type, price);
        }
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        saved = true;
        dispose();
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblField1 = new javax.swing.JLabel();
        cmbField1 = new javax.swing.JComboBox<>();
        lblField2 = new javax.swing.JLabel();
        cmbField2 = new javax.swing.JComboBox<>();
        lblPrice = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Catalogue Item");
        setResizable(false);
        getContentPane().setLayout(null);

        lblName.setText("Name:");
        getContentPane().add(lblName);
        lblName.setBounds(20, 20, 140, 20);

        getContentPane().add(txtName);
        txtName.setBounds(170, 18, 270, 26);

        lblField1.setText("Form:");
        getContentPane().add(lblField1);
        lblField1.setBounds(20, 54, 140, 20);

        cmbField1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cmbField1.addActionListener(this::cmbField1ActionPerformed);
        getContentPane().add(cmbField1);
        cmbField1.setBounds(170, 52, 270, 26);

        lblField2.setText("Type:");
        getContentPane().add(lblField2);
        lblField2.setBounds(20, 88, 140, 20);

        cmbField2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        getContentPane().add(cmbField2);
        cmbField2.setBounds(170, 86, 270, 26);

        lblPrice.setText("Price (RM):");
        getContentPane().add(lblPrice);
        lblPrice.setBounds(20, 122, 140, 20);

        getContentPane().add(txtPrice);
        txtPrice.setBounds(170, 120, 270, 26);

        btnSave.setBackground(new java.awt.Color(38, 117, 154));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);
        getContentPane().add(btnSave);
        btnSave.setBounds(170, 170, 100, 36);

        btnCancel.setBackground(new java.awt.Color(150, 150, 150));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel);
        btnCancel.setBounds(290, 170, 100, 36);

        setBounds(0, 0, 480, 250);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbField1;
    private javax.swing.JComboBox<String> cmbField2;
    private javax.swing.JLabel lblField1;
    private javax.swing.JLabel lblField2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
