/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Admin;

import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sascha
 */
public class DepartmentAssignDialog extends javax.swing.JDialog {

    private final AdminServices admin;
    private final int doctorId;
    private final ArrayList<Integer> deptIds = new ArrayList<>();
    private boolean saved = false;

    public DepartmentAssignDialog(Frame parent, AdminServices admin, int doctorId, String doctorName, String currentDept) {
        super(parent, true);
        this.admin = admin;
        this.doctorId = doctorId;
        initComponents();
        setLocationRelativeTo(parent);

        lblDoctorInfo.setText("Doctor: " + doctorName);
        lblCurrentDept.setText("Current department: " + currentDept);

        deptIds.clear();
        ArrayList<String> labels = new ArrayList<>();
        for (Object[] row : admin.getAssignableDepartments()) {
            deptIds.add((Integer) row[0]);
            labels.add((String) row[1]);
        }
        cmbDept.setModel(new javax.swing.DefaultComboBoxModel<>(labels.toArray(new String[0])));
    }

    public boolean isSaved() {
        return saved;
    }

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {
        int index = cmbDept.getSelectedIndex();
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Please select a department.");
            return;
        }
        String result = admin.assignDoctorToDepartment(doctorId, deptIds.get(index));
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        saved = true;
        dispose();
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDoctorInfo = new javax.swing.JLabel();
        lblCurrentDept = new javax.swing.JLabel();
        lblNewDept = new javax.swing.JLabel();
        cmbDept = new javax.swing.JComboBox<>();
        btnAssign = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reassign Doctor");
        setResizable(false);
        getContentPane().setLayout(null);

        lblDoctorInfo.setFont(new java.awt.Font("Segoe UI", 1, 13));
        lblDoctorInfo.setText("Doctor:");
        getContentPane().add(lblDoctorInfo);
        lblDoctorInfo.setBounds(20, 20, 380, 24);

        lblCurrentDept.setText("Current department:");
        getContentPane().add(lblCurrentDept);
        lblCurrentDept.setBounds(20, 50, 380, 24);

        lblNewDept.setText("Reassign to:");
        getContentPane().add(lblNewDept);
        lblNewDept.setBounds(20, 90, 200, 20);

        cmbDept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        getContentPane().add(cmbDept);
        cmbDept.setBounds(20, 114, 380, 26);

        btnAssign.setBackground(new java.awt.Color(38, 117, 154));
        btnAssign.setForeground(new java.awt.Color(255, 255, 255));
        btnAssign.setText("Assign");
        btnAssign.addActionListener(this::btnAssignActionPerformed);
        getContentPane().add(btnAssign);
        btnAssign.setBounds(110, 160, 100, 36);

        btnCancel.setBackground(new java.awt.Color(150, 150, 150));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel);
        btnCancel.setBounds(230, 160, 100, 36);

        setBounds(0, 0, 420, 240);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cmbDept;
    private javax.swing.JLabel lblCurrentDept;
    private javax.swing.JLabel lblDoctorInfo;
    private javax.swing.JLabel lblNewDept;
    // End of variables declaration//GEN-END:variables
}
