/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Admin;

import java.awt.Frame;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sascha
 */
public class ImagingScheduleDialog extends javax.swing.JDialog {

    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("dd-MM-yyyy");

    private final AdminServices admin;
    private final int requestId;
    private final ArrayList<Integer> roomIds = new ArrayList<>();
    private boolean saved = false;

    public ImagingScheduleDialog(Frame parent, AdminServices admin, int requestId, String serviceName,
            String patientName, String requestDate) {
        super(parent, true);
        this.admin = admin;
        this.requestId = requestId;
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Schedule Imaging");

        lblInfo.setText("<html>" + serviceName + " &mdash; " + patientName
                + "<br>Requested: " + requestDate + "</html>");

        roomIds.clear();
        ArrayList<String> labels = new ArrayList<>();
        for (Object[] row : admin.getImagingRoomsForRequest(requestId)) {
            roomIds.add((Integer) row[0]);
            labels.add((String) row[1]);
        }
        cmbRoom.setModel(new javax.swing.DefaultComboBoxModel<>(labels.toArray(new String[0])));
        txtDate.setText(LocalDate.now().format(DATE_FORMAT));
    }

    public boolean isSaved() {
        return saved;
    }

    private void btnScheduleActionPerformed(java.awt.event.ActionEvent evt) {
        int roomIndex = cmbRoom.getSelectedIndex();
        if (roomIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select an imaging room.");
            return;
        }
        String result = admin.scheduleImaging(requestId, roomIds.get(roomIndex),
                txtDate.getText(), txtStart.getText(), txtEnd.getText());
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        saved = true;
        dispose();
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo = new javax.swing.JLabel();
        lblRoom = new javax.swing.JLabel();
        cmbRoom = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        lblStart = new javax.swing.JLabel();
        txtStart = new javax.swing.JTextField();
        lblEnd = new javax.swing.JLabel();
        txtEnd = new javax.swing.JTextField();
        lblHint = new javax.swing.JLabel();
        btnSchedule = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Schedule Imaging");
        setResizable(false);
        getContentPane().setLayout(null);

        lblInfo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblInfo);
        lblInfo.setBounds(20, 15, 400, 40);

        lblRoom.setText("Imaging Room:");
        getContentPane().add(lblRoom);
        lblRoom.setBounds(20, 65, 140, 20);

        cmbRoom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        getContentPane().add(cmbRoom);
        cmbRoom.setBounds(20, 89, 400, 26);

        lblDate.setText("Date (dd-MM-yyyy):");
        getContentPane().add(lblDate);
        lblDate.setBounds(20, 129, 140, 20);

        getContentPane().add(txtDate);
        txtDate.setBounds(20, 153, 400, 26);

        lblStart.setText("Start Time (HH:mm):");
        getContentPane().add(lblStart);
        lblStart.setBounds(20, 193, 190, 20);

        getContentPane().add(txtStart);
        txtStart.setBounds(20, 217, 190, 26);

        lblEnd.setText("End Time (HH:mm):");
        getContentPane().add(lblEnd);
        lblEnd.setBounds(230, 193, 190, 20);

        getContentPane().add(txtEnd);
        txtEnd.setBounds(230, 217, 190, 26);

        lblHint.setFont(new java.awt.Font("Segoe UI", 2, 11));
        lblHint.setText("Times must be in 30-minute increments.");
        getContentPane().add(lblHint);
        lblHint.setBounds(20, 250, 400, 18);

        btnSchedule.setBackground(new java.awt.Color(38, 117, 154));
        btnSchedule.setForeground(new java.awt.Color(255, 255, 255));
        btnSchedule.setText("Schedule");
        btnSchedule.addActionListener(this::btnScheduleActionPerformed);
        getContentPane().add(btnSchedule);
        btnSchedule.setBounds(120, 285, 130, 36);

        btnCancel.setBackground(new java.awt.Color(150, 150, 150));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel);
        btnCancel.setBounds(260, 285, 100, 36);

        setBounds(0, 0, 440, 365);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSchedule;
    private javax.swing.JComboBox<String> cmbRoom;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEnd;
    private javax.swing.JLabel lblHint;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblStart;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtEnd;
    private javax.swing.JTextField txtStart;
    // End of variables declaration//GEN-END:variables
}
