/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Admin;

import java.awt.Frame;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Shows the computed itemised breakdown for a closed case before the admin
 * confirms generating its invoice.
 *
 * @author Sascha
 */
public class InvoiceDetailDialog extends javax.swing.JDialog {

    private final AdminServices admin;
    private final int caseId;
    private boolean saved = false;

    public InvoiceDetailDialog(Frame parent, AdminServices admin, int caseId, String caseLabel) {
        super(parent, true);
        this.admin = admin;
        this.caseId = caseId;
        initComponents();
        setLocationRelativeTo(parent);

        lblHeader.setText(caseLabel);

        DefaultTableModel model = (DefaultTableModel) tblItems.getModel();
        model.setRowCount(0);
        double total = 0;
        for (Object[] row : admin.previewInvoiceItems(caseId)) {
            model.addRow(row);
            try {
                total += Double.parseDouble((String) row[2]);
            } catch (Exception e) {
                // ignore an unparseable row when totalling
            }
        }
        lblTotal.setText(String.format(Locale.US, "Total: RM %.2f", total));
    }

    public boolean isSaved() {
        return saved;
    }

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {
        String result = admin.generateInvoice(caseId);
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        saved = true;
        dispose();
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        scrItems = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        btnGenerate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Generate Invoice");
        setResizable(false);
        getContentPane().setLayout(null);

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lblHeader.setText("Case");
        getContentPane().add(lblHeader);
        lblHeader.setBounds(20, 15, 440, 24);

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Item", "Qty", "Amount (RM)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItems.getTableHeader().setReorderingAllowed(false);
        tblItems.setSelectionBackground(new java.awt.Color(38, 117, 154));
        tblItems.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrItems.setViewportView(tblItems);
        getContentPane().add(scrItems);
        scrItems.setBounds(20, 50, 440, 280);

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lblTotal.setText("Total: RM 0.00");
        getContentPane().add(lblTotal);
        lblTotal.setBounds(20, 340, 440, 26);

        btnGenerate.setBackground(new java.awt.Color(38, 117, 154));
        btnGenerate.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerate.setText("Generate Invoice");
        btnGenerate.addActionListener(this::btnGenerateActionPerformed);
        getContentPane().add(btnGenerate);
        btnGenerate.setBounds(140, 385, 160, 36);

        btnCancel.setBackground(new java.awt.Color(150, 150, 150));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel);
        btnCancel.setBounds(310, 385, 100, 36);

        setBounds(0, 0, 500, 460);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JScrollPane scrItems;
    private javax.swing.JTable tblItems;
    // End of variables declaration//GEN-END:variables
}
