/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Admin;

import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sascha
 */
public class LabResultDialog extends javax.swing.JDialog {

    private final AdminServices admin;
    private final int requestId;
    private boolean saved = false;

    public LabResultDialog(Frame parent, AdminServices admin, int requestId, String serviceName,
            String patientName, String requestDate, String remarks) {
        super(parent, true);
        this.admin = admin;
        this.requestId = requestId;
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Enter Lab Result");

        lblInfo.setText("<html>" + serviceName + " &mdash; " + patientName
                + "<br>Requested: " + requestDate
                + (remarks == null || remarks.isBlank() ? "" : "<br>Remarks: " + remarks) + "</html>");
    }

    public boolean isSaved() {
        return saved;
    }

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {
        String result = admin.submitLabResult(requestId, txtResult.getText());
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        saved = true;
        dispose();
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInfo = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        scrResult = new javax.swing.JScrollPane();
        txtResult = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter Lab Result");
        setResizable(false);
        getContentPane().setLayout(null);

        lblInfo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblInfo);
        lblInfo.setBounds(20, 15, 400, 70);

        lblResult.setText("Result:");
        getContentPane().add(lblResult);
        lblResult.setBounds(20, 95, 100, 20);

        txtResult.setLineWrap(true);
        txtResult.setWrapStyleWord(true);
        txtResult.setRows(6);
        scrResult.setViewportView(txtResult);
        getContentPane().add(scrResult);
        scrResult.setBounds(20, 118, 400, 140);

        btnSubmit.setBackground(new java.awt.Color(38, 117, 154));
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit Result");
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);
        getContentPane().add(btnSubmit);
        btnSubmit.setBounds(100, 272, 160, 36);

        btnCancel.setBackground(new java.awt.Color(150, 150, 150));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel);
        btnCancel.setBounds(270, 272, 100, 36);

        setBounds(0, 0, 460, 350);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblResult;
    private javax.swing.JScrollPane scrResult;
    private javax.swing.JTextArea txtResult;
    // End of variables declaration//GEN-END:variables
}
