/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Admin;

import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Records the single receipt for one unpaid invoice: a payment method, and an
 * insurance provider only when the method is "Insurance".
 *
 * @author Sascha
 */
public class ReceiptDialog extends javax.swing.JDialog {

    private static final String[] METHOD_LABELS = {"Cash", "Card", "Online Transfer", "Insurance"};
    private static final String[] METHOD_VALUES = {"cash", "card", "online_transfer", "insurance"};

    private final AdminServices admin;
    private final int invoiceId;
    private final ArrayList<Integer> insuranceIds = new ArrayList<>();
    private boolean saved = false;

    public ReceiptDialog(Frame parent, AdminServices admin, int invoiceId, String caseLabel, String totalAmount) {
        super(parent, true);
        this.admin = admin;
        this.invoiceId = invoiceId;
        initComponents();
        setLocationRelativeTo(parent);

        lblHeader.setText(caseLabel);
        lblTotalAmount.setText("Total: RM " + totalAmount);

        cmbMethod.setModel(new javax.swing.DefaultComboBoxModel<>(METHOD_LABELS));

        insuranceIds.clear();
        ArrayList<String> insuranceLabels = new ArrayList<>();
        for (Object[] row : admin.getInsuranceNetworks()) {
            insuranceIds.add((Integer) row[0]);
            insuranceLabels.add((String) row[1]);
        }
        cmbInsurance.setModel(new javax.swing.DefaultComboBoxModel<>(insuranceLabels.toArray(new String[0])));
        refreshInsuranceVisibility();
    }

    public boolean isSaved() {
        return saved;
    }

    private void refreshInsuranceVisibility() {
        boolean isInsurance = cmbMethod.getSelectedIndex() == METHOD_VALUES.length - 1;
        lblInsurance.setVisible(isInsurance);
        cmbInsurance.setVisible(isInsurance);
    }

    private void cmbMethodActionPerformed(java.awt.event.ActionEvent evt) {
        refreshInsuranceVisibility();
    }

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {
        int methodIndex = cmbMethod.getSelectedIndex();
        if (methodIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a payment method.");
            return;
        }
        String method = METHOD_VALUES[methodIndex];
        Integer insuranceId = null;
        if (method.equals("insurance")) {
            int insuranceIndex = cmbInsurance.getSelectedIndex();
            if (insuranceIndex < 0) {
                JOptionPane.showMessageDialog(this, "Please select an insurance provider.");
                return;
            }
            insuranceId = insuranceIds.get(insuranceIndex);
        }
        String result = admin.recordPayment(invoiceId, method, insuranceId);
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        saved = true;
        dispose();
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblTotalAmount = new javax.swing.JLabel();
        lblMethod = new javax.swing.JLabel();
        cmbMethod = new javax.swing.JComboBox<>();
        lblInsurance = new javax.swing.JLabel();
        cmbInsurance = new javax.swing.JComboBox<>();
        btnConfirm = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Record Payment");
        setResizable(false);
        getContentPane().setLayout(null);

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 14));
        lblHeader.setText("Case");
        getContentPane().add(lblHeader);
        lblHeader.setBounds(20, 15, 440, 24);

        lblTotalAmount.setFont(new java.awt.Font("Segoe UI", 1, 13));
        lblTotalAmount.setText("Total: RM 0.00");
        getContentPane().add(lblTotalAmount);
        lblTotalAmount.setBounds(20, 50, 440, 20);

        lblMethod.setText("Payment Method:");
        getContentPane().add(lblMethod);
        lblMethod.setBounds(20, 90, 140, 20);

        cmbMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        cmbMethod.addActionListener(this::cmbMethodActionPerformed);
        getContentPane().add(cmbMethod);
        cmbMethod.setBounds(170, 88, 270, 26);

        lblInsurance.setText("Insurance Provider:");
        getContentPane().add(lblInsurance);
        lblInsurance.setBounds(20, 124, 140, 20);

        cmbInsurance.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        getContentPane().add(cmbInsurance);
        cmbInsurance.setBounds(170, 122, 270, 26);

        btnConfirm.setBackground(new java.awt.Color(38, 117, 154));
        btnConfirm.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirm.setText("Confirm Payment");
        btnConfirm.addActionListener(this::btnConfirmActionPerformed);
        getContentPane().add(btnConfirm);
        btnConfirm.setBounds(150, 175, 160, 36);

        btnCancel.setBackground(new java.awt.Color(150, 150, 150));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel);
        btnCancel.setBounds(320, 175, 100, 36);

        setBounds(0, 0, 480, 260);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirm;
    private javax.swing.JComboBox<String> cmbInsurance;
    private javax.swing.JComboBox<String> cmbMethod;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblInsurance;
    private javax.swing.JLabel lblMethod;
    private javax.swing.JLabel lblTotalAmount;
    // End of variables declaration//GEN-END:variables
}
