/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Admin;

import java.awt.Frame;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Sascha
 */
public class WardEditDialog extends javax.swing.JDialog {

    private final AdminServices admin;
    private final Integer editingWardId;
    private final ArrayList<Integer> deptIds = new ArrayList<>();
    private boolean saved = false;

    public WardEditDialog(Frame parent, AdminServices admin, Integer editingWardId) {
        super(parent, true);
        this.admin = admin;
        this.editingWardId = editingWardId;
        initComponents();
        setLocationRelativeTo(parent);

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"male", "female"}));

        deptIds.clear();
        ArrayList<String> labels = new ArrayList<>();
        for (Object[] row : admin.getDepartments()) {
            deptIds.add((Integer) row[0]);
            labels.add((String) row[1]);
        }
        cmbDept.setModel(new javax.swing.DefaultComboBoxModel<>(labels.toArray(new String[0])));

        if (editingWardId == null) {
            setTitle("Add Ward");
        } else {
            setTitle("Edit Ward");
            String[] detail = admin.getWardDetail(editingWardId);
            if (detail != null) {
                int deptIndex = deptIds.indexOf(Integer.parseInt(detail[0]));
                if (deptIndex >= 0) {
                    cmbDept.setSelectedIndex(deptIndex);
                }
                cmbGender.setSelectedItem(detail[1]);
                txtCapacity.setText(detail[2]);
            }
            cmbDept.setEnabled(false);
        }
    }

    public boolean isSaved() {
        return saved;
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {
        int deptIndex = cmbDept.getSelectedIndex();
        if (deptIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a department.");
            return;
        }
        String gender = (String) cmbGender.getSelectedItem();
        int capacity;
        try {
            capacity = Integer.parseInt(txtCapacity.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid capacity.");
            return;
        }

        String result = editingWardId == null
                ? admin.addWard(deptIds.get(deptIndex), gender, capacity)
                : admin.updateWard(editingWardId, gender, capacity);
        if (result != null) {
            JOptionPane.showMessageDialog(this, result);
            return;
        }
        saved = true;
        dispose();
    }

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDept = new javax.swing.JLabel();
        cmbDept = new javax.swing.JComboBox<>();
        lblGender = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        lblCapacity = new javax.swing.JLabel();
        txtCapacity = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ward Details");
        setResizable(false);
        getContentPane().setLayout(null);

        lblDept.setText("Department:");
        getContentPane().add(lblDept);
        lblDept.setBounds(20, 20, 140, 20);

        cmbDept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        getContentPane().add(cmbDept);
        cmbDept.setBounds(20, 44, 340, 26);

        lblGender.setText("Gender:");
        getContentPane().add(lblGender);
        lblGender.setBounds(20, 84, 140, 20);

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        getContentPane().add(cmbGender);
        cmbGender.setBounds(20, 108, 340, 26);

        lblCapacity.setText("Capacity:");
        getContentPane().add(lblCapacity);
        lblCapacity.setBounds(20, 148, 140, 20);

        getContentPane().add(txtCapacity);
        txtCapacity.setBounds(20, 172, 340, 26);

        btnSave.setBackground(new java.awt.Color(38, 117, 154));
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);
        getContentPane().add(btnSave);
        btnSave.setBounds(80, 220, 100, 36);

        btnCancel.setBackground(new java.awt.Color(150, 150, 150));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);
        getContentPane().add(btnCancel);
        btnCancel.setBounds(200, 220, 100, 36);

        setBounds(0, 0, 380, 300);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbDept;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel lblCapacity;
    private javax.swing.JLabel lblDept;
    private javax.swing.JLabel lblGender;
    private javax.swing.JTextField txtCapacity;
    // End of variables declaration//GEN-END:variables
}
