/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Doctor;

/**
 *
 * @author Sascha
 */
public class ReviewDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReviewDialog.class.getName());

    /**
     * Creates new form ReviewDialog
     */
    public ReviewDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    // Shows the full details of one review. Nothing here is editable.
    public ReviewDialog(java.awt.Frame parent, boolean modal, int consultId, String patientName,
            String rating, String dateReviewed, String comments) {
        super(parent, modal);
        initComponents();

        lblConsultationId.setText("Consultation #" + consultId);
        lblPatientName.setText("Patient: " + patientName);
        lblRating.setText("Rating: " + rating + " / 5");
        lblDateReviewed.setText("Reviewed on: " + dateReviewed);
        lblComments.setText("<html>" + comments + "</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReviewHeader = new javax.swing.JLabel();
        lblConsultationId = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblRating = new javax.swing.JLabel();
        lblDateReviewed = new javax.swing.JLabel();
        lblCommentsHeader = new javax.swing.JLabel();
        lblComments = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Review Details");
        setModal(true);
        setName("reviews"); // NOI18N
        setPreferredSize(new java.awt.Dimension(475, 390));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblReviewHeader.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblReviewHeader.setText("lblReviewHeader");
        getContentPane().add(lblReviewHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 26));

        lblConsultationId.setText("lblConsultationId");
        getContentPane().add(lblConsultationId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 56, 420, 20));

        lblPatientName.setText("Patient: ");
        getContentPane().add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 420, 20));

        lblRating.setText("Rating: ");
        getContentPane().add(lblRating, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 104, 420, 20));

        lblDateReviewed.setText("Reviewed on: ");
        getContentPane().add(lblDateReviewed, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 128, 420, 20));

        lblCommentsHeader.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCommentsHeader.setText("Comments:");
        getContentPane().add(lblCommentsHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 300, 20));

        lblComments.setText("<html></html>");
        lblComments.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblComments, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 184, 420, 100));

        btnClose.setBackground(new java.awt.Color(38, 117, 154));
        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClose.setForeground(new java.awt.Color(255, 255, 255));
        btnClose.setText("Close");
        btnClose.addActionListener(this::btnClose);
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 420, 36));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClose(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose
        dispose();
    }//GEN-LAST:event_btnClose


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ReviewDialog dialog = new ReviewDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblComments;
    private javax.swing.JLabel lblCommentsHeader;
    private javax.swing.JLabel lblConsultationId;
    private javax.swing.JLabel lblDateReviewed;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblRating;
    private javax.swing.JLabel lblReviewHeader;
    // End of variables declaration//GEN-END:variables
}
